import { copyFile, mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
const require = createRequire(import.meta.url);
const vad = dirname(require.resolve('@ricky0123/vad-web'));
const ort = dirname(require.resolve('onnxruntime-web/wasm'));
const target = new URL('../public/voice/', import.meta.url);
await mkdir(target, { recursive: true });
for (const name of ['silero_vad_v5.onnx', 'vad.worklet.bundle.min.js']) await copyFile(join(vad, name), new URL(name, target));
for (const name of ['ort-wasm-simd-threaded.mjs', 'ort-wasm-simd-threaded.wasm']) await copyFile(join(ort, name), new URL(name, target));
