"""
cognition/causal_mechanism_model.py  (v60)

Reads WSDM records and identifies which context dimensions causally
explain outcome variance rather than merely correlate with it.

Method: variance decomposition by context partition.
For each action type with >= MIN_RECORDS records:
    Partition records by each context dimension (high/low split at median).
    Compute outcome variance within each partition.
    Causal relevance of dimension d = reduction in variance when conditioning on d.
    High reduction = d is causally informative for this action type.

Outputs a CausalSignature per action type:
    {
      "philosophical": {
        "user_trust":         0.61,   # high causal relevance
        "cognitive_energy":   0.44,
        "novelty_drive":      0.12,   # low — probably noise
        "mechanism_summary":  "Philosophical engagement outcomes are
                               primarily explained by relational trust
                               and current cognitive energy.  Novelty
                               drive and attention are not causally
                               informative."
      }
    }

This upgrades WSDM from:
    "philosophical interactions tend to cost 0.09 energy"
to:
    "philosophical interactions cost more when cognitive_energy is below 0.40
     (trust is irrelevant to cost) but trust is the primary driver of whether
     they produce relational gain"

The mechanism summary is generated by the LLM from the variance data.
Temperature 0.5 — deliberate.

Runs every CAUSAL_EVERY_N slow cycles.  Requires MIN_RECORDS per
action type before producing any output.  Results cached and updated
incrementally as new records arrive.
"""

from __future__ import annotations
import json, logging, math, threading, time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

CAUSAL_EVERY_N  = 60
MIN_RECORDS     = 20    # per action type
SAVE_PATH       = "data/persona/causal_mechanisms.json"

CTX_DIMS = [
    "cognitive_energy","social_energy","attention",
    "self_model_confidence","novelty_drive",
    "user_trust","interaction_norm","topic_diversity",
]
OUTCOME_DIMS = ["cognitive_energy","social_energy","user_trust","engagement_signal"]


@dataclass
class CausalSignature:
    action_type:       str
    causal_relevance:  Dict[str, float]   # dim → relevance [0,1]
    mechanism_summary: str
    record_count:      int
    computed_at:       float = field(default_factory=time.time)


class CausalMechanismModel:
    def __init__(self, organism: Any, ai_system: Any, path: str = SAVE_PATH):
        self._organism = organism
        self._ai       = ai_system
        self._path     = Path(path)
        self._lock     = threading.Lock()
        self._sigs:    Dict[str, CausalSignature] = {}
        self._load()
        logger.info(f"[CausalMechanism] Init — {len(self._sigs)} signatures")

    def tick(self, slow_cycle: int) -> None:
        if slow_cycle % CAUSAL_EVERY_N != 0 or slow_cycle == 0: return
        threading.Thread(target=self._run, daemon=True, name="cm-run").start()

    def get_signature(self, action_type: str) -> Optional[CausalSignature]:
        return self._sigs.get(action_type)

    def causal_advisory(self, action_type: str, context: List[float]) -> str:
        """Return a mechanism-aware advisory for the prompt."""
        sig = self._sigs.get(action_type)
        if not sig: return ""
        top = sorted(sig.causal_relevance.items(), key=lambda x: x[1], reverse=True)[:2]
        if not top or top[0][1] < 0.35: return ""
        parts = []
        for dim, rel in top:
            if rel < 0.30: continue
            idx = CTX_DIMS.index(dim) if dim in CTX_DIMS else -1
            val = context[idx] if 0 <= idx < len(context) else None
            if val is not None:
                parts.append(f"{dim.replace('_',' ')}={val:.2f}(causal={rel:.2f})")
        if not parts: return ""
        return f"[Causal note] {action_type}: primary drivers {', '.join(parts)}."

    def status(self) -> Dict:
        return {
            "signatures": len(self._sigs),
            "action_types": list(self._sigs.keys()),
        }

    def _run(self) -> None:
        try:
            loop = getattr(self._organism, '_loop', None)
            wsdm = getattr(loop, '_world_self_dynamics', None) if loop else None
            if not wsdm: return
            by_type: Dict[str, list] = {}
            for rec in wsdm._records:
                by_type.setdefault(rec.action_type, []).append(rec)
            for at, recs in by_type.items():
                if len(recs) < MIN_RECORDS: continue
                relevance = self._compute_relevance(recs)
                summary   = self._generate_summary(at, relevance, recs)
                sig = CausalSignature(
                    action_type=at, causal_relevance=relevance,
                    mechanism_summary=summary, record_count=len(recs),
                )
                with self._lock:
                    self._sigs[at] = sig
            self._save()
            logger.info(f"[CausalMechanism] Updated {len(by_type)} signatures")
        except Exception as e:
            logger.debug(f"[CausalMechanism] _run error: {e}")

    def _compute_relevance(self, records: list) -> Dict[str, float]:
        """
        For each context dimension, compute variance reduction when
        conditioning on that dimension (median split).
        """
        relevance: Dict[str, float] = {}
        # Total variance in outcomes
        all_trust = [r.world_delta[0] for r in records if r.world_delta]
        if not all_trust: return {}
        total_var = self._variance(all_trust)
        if total_var < 1e-9:
            return {d: 0.0 for d in CTX_DIMS}

        for i, dim in enumerate(CTX_DIMS):
            vals = [r.context_before[i] for r in records
                    if i < len(r.context_before)]
            if not vals: continue
            median = sorted(vals)[len(vals)//2]
            low_out  = [r.world_delta[0] for r in records
                        if i < len(r.context_before) and r.context_before[i] <= median
                        and r.world_delta]
            high_out = [r.world_delta[0] for r in records
                        if i < len(r.context_before) and r.context_before[i] > median
                        and r.world_delta]
            within_var = (
                self._variance(low_out)  * len(low_out) +
                self._variance(high_out) * len(high_out)
            ) / max(1, len(low_out) + len(high_out))
            reduction = max(0.0, 1.0 - within_var / max(total_var, 1e-9))
            relevance[dim] = round(min(1.0, reduction), 4)
        return relevance

    @staticmethod
    def _variance(vals: list) -> float:
        if len(vals) < 2: return 0.0
        m = sum(vals)/len(vals)
        return sum((v-m)**2 for v in vals)/len(vals)

    def _generate_summary(self, action_type: str,
                           relevance: Dict[str, float],
                           records: list) -> str:
        top = sorted(relevance.items(), key=lambda x: x[1], reverse=True)[:3]
        top_str = ", ".join(f"{d}={v:.2f}" for d,v in top)
        prompt = (
            f"Action type: {action_type}\n"
            f"Causal relevance scores (variance reduction): {top_str}\n"
            f"Records analysed: {len(records)}\n\n"
            f"In 2 sentences, explain what these scores mean mechanistically: "
            f"which context dimensions actually drive outcomes for this action type "
            f"and which are noise. Be specific, not vague."
        )
        try:
            from core.llm_scheduler import llm_scheduler
            res = ""
            with llm_scheduler.sync_slot(priority=5, skip_if_busy=True,
                                          caller="causal_mechanism") as ok:
                if ok:
                    res = self._ai.get_response(
                        messages=[{"role":"user","content":prompt}],
                        max_tokens=120, temperature=0.5,
                    ) or ""
            return res.strip()[:300]
        except Exception:
            return f"Primary drivers: {top_str}"

    def _save(self) -> None:
        try:
            self._path.parent.mkdir(parents=True, exist_ok=True)
            with self._lock:
                data = {at: asdict(s) for at, s in self._sigs.items()}
                data["_meta"] = {"version":"v60","ts":time.time()}
            with open(self._path,"w") as f: json.dump(data,f,indent=2)
        except Exception as e:
            logger.debug(f"[CausalMechanism] save error: {e}")

    def _load(self) -> None:
        try:
            if not self._path.exists(): return
            data = json.loads(self._path.read_text())
            for at, d in data.items():
                if at.startswith("_"): continue
                self._sigs[at] = CausalSignature(**{
                    k:v for k,v in d.items()
                    if k in CausalSignature.__dataclass_fields__
                })
        except Exception as e:
            logger.warning(f"[CausalMechanism] load error: {e}")
