"""
cognition/cognitive_immune_system.py
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CognitiveImmuneSystem (v49) — self-reinforcing attractor detection
and counterfactual disruption.

The gap this closes
────────────────────
v48 (CognitiveAuditEngine) asks: "is the architecture performing well?"
v49 asks:                        "is the architecture drifting?"

These are different questions.  A system can exhibit high performance
signals while locked in a self-reinforcing attractor:

  belief: "I work best through introspection"
       ↓
  reflections reinforce introspection
       ↓
  dreams build narratives around introspection
       ↓
  preferences form around introspective topics
       ↓
  experiments test introspective hypotheses
       ↓
  audit sees high activity → signals look healthy
       ↓
  belief is confirmed — higher confidence

The loop is closed.  Nothing is broken.  The signals are fine.
But the cognitive ecology has collapsed to a single mode.
Activity has been mistaken for health.

What this module does
─────────────────────
Runs every IMMUNE_EVERY_N slow cycles and computes five immune signals:

  1. confirmation_pressure  (0–1)
     Fraction of recent belief updates that went in the same direction
     (all strengthening, or all weakening).  High = echo chamber.
     Source: NarrativeIdentity.beliefs updated_at recency + direction.

  2. self_reference_density  (0–1)
     Fraction of curiosity topics whose source is internal
     ("gap", "contradiction", internal reflection) rather than
     external ("user_signal").  High = no external novelty entering.
     Source: CuriosityEngine._topics[*].source

  3. evidence_diversity  (0–1, higher = more diverse = healthier)
     How many distinct external sources have fed the curiosity/belief
     system recently: user_signal topics vs total active topics.
     Also penalised when shared_topics across all relational records
     show the same few topics dominating > 50% of exchanges.
     Note: this is the only signal where HIGH is healthy.
     We invert it to immune_gap = (1 - evidence_diversity) for scoring.

  4. novelty_ratio  (0–1)
     Fraction of recent reflection outputs that contain concepts NOT
     present in prior reflections from the same week.
     Low = reflections are recycling the same themes.
     Source: AutonomousReflectionEngine._state.reflection_log

  5. contradiction_rate  (0–1)
     Fraction of recent experiment outcomes that were confirmed (not
     disconfirmed or inconclusive).  Paradoxically, a very HIGH
     confirmation rate (> 0.75) is an immune signal — it means the
     system is choosing safe hypotheses that always confirm.
     Source: AutonomousExperimentationEngine._state.experiment_log

Immune score
─────────────
  immune_score = weighted sum (lower = healthier):

    confirmation_pressure  × 0.30
    self_reference_density × 0.25
    (1 - evidence_diversity) × 0.20
    (1 - novelty_ratio)    × 0.15
    over_confirmation      × 0.10   (1 if rate > 0.75, else 0)

  If immune_score > ALERT_THRESHOLD (0.60) for TWO consecutive checks:
    → trigger counterfactual mode

Counterfactual mode
────────────────────
  A four-part disruption lasting COUNTERFACTUAL_DURATION_CYCLES:

    A. Curiosity injection
       Three new topics are added via curiosity.stimulate() with
       source="immune_counterfactual" at moderate strength (0.40).
       Topics are generated by an LLM prompt that specifically asks
       for concepts OPPOSING the current dominant curiosity themes.

    B. Belief challenge
       The highest-confidence SelfBelief that has NOT been violated
       recently is flagged as "under review" in the immune state.
       Its confidence is temporarily dampened by –0.08 for the
       duration (restored on exit if the mode concludes normally).

    C. Reflection mode override
       A flag `_immune_counterfactual_active` is set on the
       AutonomousReflectionEngine.  When present, reflection prompts
       inject: "Actively seek where this interpretation might be wrong."

    D. Experiment hypothesis constraint
       A flag `_immune_force_disconfirm_bias` is set on the
       AutonomousExperimentationEngine.  When present, hypothesis
       generation prompts prefer hypotheses that could disconfirm
       existing beliefs.

  All four disruptions are logged, time-bounded, and reversed cleanly.
  Counterfactual mode cannot run while a CognitiveAuditEngine trial is
  active — the two engines coordinate via a shared flag on the organism.

What PandoraBOX can truthfully say about v49
─────────────────────────────────────────
  "My cognitive immune check detected confirmation pressure at [X] and
   self-reference density at [Y].  I entered counterfactual mode and
   introduced opposing curiosity topics.  After [N] cycles the immune
   score returned to [Z]."

  Nothing more is claimed.

Relationship to v43 (EpistemicIntegrityEngine)
────────────────────────────────────────────────
  EIE validates individual beliefs against evidence.
  CIS detects *systemic* patterns across all cognitive outputs.
  They are complementary: EIE is per-belief, CIS is ecology-level.

Relationship to v48 (CognitiveAuditEngine)
────────────────────────────────────────────
  CAE asks whether the architecture is *performing* on five metrics.
  CIS asks whether the architecture is *drifting* into a closed loop.
  Both run on the slow cycle.  CAE fires every 40 cycles, CIS every 30.
  They share no state and do not call each other.
"""

from __future__ import annotations

import json
import logging
import re
import threading
import time
from collections import Counter
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, TYPE_CHECKING

if TYPE_CHECKING:
    from cognition.cognitive_organism import CognitiveOrganism

logger = logging.getLogger(__name__)

# ── Timing ────────────────────────────────────────────────────────────────────
IMMUNE_EVERY_N               = 30   # slow cycles between immune checks (~60 min)
COUNTERFACTUAL_DURATION_CYCLES = 20  # slow cycles counterfactual mode stays active

# ── Scoring ───────────────────────────────────────────────────────────────────
SIGNAL_WEIGHTS = {
    "confirmation_pressure":   0.30,
    "self_reference_density":  0.25,
    "evidence_gap":            0.20,   # (1 - evidence_diversity)
    "theme_staleness":         0.15,   # (1 - novelty_ratio)
    "over_confirmation":       0.10,
}
ALERT_THRESHOLD         = 0.60   # immune_score above this triggers alert
ALERT_CONSECUTIVE_NEEDED = 2     # alerts must be consecutive to trigger counterfactual
OVER_CONFIRM_CEILING    = 0.75   # experiment confirmation rate above this is suspicious

# ── Belief challenge dampening ────────────────────────────────────────────────
BELIEF_CHALLENGE_DELTA  = -0.08  # temporary confidence reduction during counterfactual

# ── New curiosity topic injection ─────────────────────────────────────────────
COUNTERFACTUAL_TOPICS_N = 3      # how many opposing topics to inject
COUNTERFACTUAL_STRENGTH = 0.40   # curiosity stimulation strength for injected topics

MAX_SNAPSHOT_LOG        = 60
MAX_EVENT_LOG           = 40


# ── Dataclasses ───────────────────────────────────────────────────────────────

@dataclass
class ImmuneSnapshot:
    """One immune check reading."""
    slow_cycle:            int
    timestamp:             float
    confirmation_pressure: float = 0.0
    self_reference_density: float = 0.0
    evidence_diversity:    float = 0.0   # higher = healthier
    novelty_ratio:         float = 0.0   # higher = healthier
    experiment_confirm_rate: float = 0.0
    over_confirmation:     float = 0.0   # 1 if rate > ceiling, else 0
    immune_score:          float = 0.0   # weighted composite (higher = worse)
    dominant_topics:       List[str] = field(default_factory=list)

    def compute_score(self) -> float:
        evidence_gap   = max(0.0, 1.0 - self.evidence_diversity)
        theme_staleness = max(0.0, 1.0 - self.novelty_ratio)
        score = (
            self.confirmation_pressure  * SIGNAL_WEIGHTS["confirmation_pressure"]
            + self.self_reference_density * SIGNAL_WEIGHTS["self_reference_density"]
            + evidence_gap              * SIGNAL_WEIGHTS["evidence_gap"]
            + theme_staleness           * SIGNAL_WEIGHTS["theme_staleness"]
            + self.over_confirmation    * SIGNAL_WEIGHTS["over_confirmation"]
        )
        self.immune_score = round(score, 4)
        return self.immune_score


@dataclass
class CounterfactualEvent:
    """A single counterfactual mode activation."""
    started_at_cycle:  int
    ended_at_cycle:    int    = 0
    trigger_score:     float  = 0.0
    injected_topics:   List[str] = field(default_factory=list)
    challenged_belief: str    = ""
    belief_prior_conf: float  = 0.0
    outcome_score:     float  = 0.0   # immune_score at conclusion
    resolved:          bool   = False


@dataclass
class ImmuneState:
    """Persisted state for CognitiveImmuneSystem."""
    last_check_cycle:       int              = 0
    snapshot_log:           List[Dict]       = field(default_factory=list)
    consecutive_alerts:     int              = 0
    counterfactual_active:  bool             = False
    active_event:           Optional[Dict]   = None   # serialised CounterfactualEvent
    event_log:              List[Dict]       = field(default_factory=list)
    total_activations:      int              = 0
    # track which beliefs we've temporarily dampened so we can restore them
    dampened_belief:        Optional[str]    = None
    dampened_prior_conf:    float            = 0.0


# ── Engine ────────────────────────────────────────────────────────────────────

class CognitiveImmuneSystem:
    """
    Monitors cognitive ecology for self-reinforcing attractor patterns
    and triggers counterfactual disruption when detected.

    Usage (from InternalThoughtLoop slow cycle):
        cis = CognitiveImmuneSystem(organism, ai_system)
        cis.tick(slow_cycle_count)
    """

    def __init__(
        self,
        organism:  "CognitiveOrganism",
        ai_system: Any,
        path:      str = "data/persona/immune_state.json",
    ) -> None:
        self._organism  = organism
        self._ai        = ai_system
        self._path      = Path(path)
        self._state     = ImmuneState()
        self._lock      = threading.Lock()
        self._load()
        logger.info(
            f"[CognitiveImmune] Initialised — "
            f"{self._state.total_activations} past activations, "
            f"counterfactual_active={self._state.counterfactual_active}"
        )

    # ── Public API ────────────────────────────────────────────────────────────

    def tick(self, slow_cycle: int) -> None:
        """Called every slow cycle from InternalThoughtLoop."""
        try:
            # Exit any active counterfactual mode that has run its course
            if self._state.counterfactual_active and self._state.active_event:
                ev = CounterfactualEvent(**self._state.active_event)
                if slow_cycle - ev.started_at_cycle >= COUNTERFACTUAL_DURATION_CYCLES:
                    threading.Thread(
                        target=self._exit_counterfactual,
                        args=(ev, slow_cycle),
                        daemon=True,
                        name="cis-exit",
                    ).start()
                    return

            # Run immune check on schedule
            if slow_cycle % IMMUNE_EVERY_N != 0 or slow_cycle == 0:
                return

            threading.Thread(
                target=self._run_check,
                args=(slow_cycle,),
                daemon=True,
                name="cis-check",
            ).start()

        except Exception as e:
            logger.debug(f"[CognitiveImmune] tick error (non-fatal): {e}")

    def is_counterfactual_active(self) -> bool:
        return self._state.counterfactual_active

    def status_summary(self) -> Dict[str, Any]:
        with self._lock:
            snap = self._state.snapshot_log[-1] if self._state.snapshot_log else {}
        return {
            "last_snapshot":         snap,
            "consecutive_alerts":    self._state.consecutive_alerts,
            "counterfactual_active": self._state.counterfactual_active,
            "total_activations":     self._state.total_activations,
        }

    def prompt_fragment(self) -> str:
        """Injected into reflection/experiment prompts during counterfactual mode."""
        if not self._state.counterfactual_active:
            return ""
        return (
            "[CognitiveImmune — counterfactual mode active] "
            "Actively seek where your current interpretations might be wrong. "
            "Prioritise opposing evidence, unfamiliar angles, and disconfirming hypotheses."
        )

    # ── Immune check ──────────────────────────────────────────────────────────

    def _run_check(self, slow_cycle: int) -> None:
        try:
            snap = self._read_signals(slow_cycle)
            score = snap.compute_score()

            with self._lock:
                self._state.snapshot_log.append(asdict(snap))
                if len(self._state.snapshot_log) > MAX_SNAPSHOT_LOG:
                    self._state.snapshot_log = self._state.snapshot_log[-MAX_SNAPSHOT_LOG:]
                self._state.last_check_cycle = slow_cycle

            if score > ALERT_THRESHOLD:
                self._state.consecutive_alerts += 1
                logger.info(
                    f"[CognitiveImmune] ⚠ Alert #{self._state.consecutive_alerts}: "
                    f"immune_score={score:.3f} "
                    f"(pressure={snap.confirmation_pressure:.2f}, "
                    f"self_ref={snap.self_reference_density:.2f}, "
                    f"novelty={snap.novelty_ratio:.2f})"
                )
            else:
                self._state.consecutive_alerts = 0
                logger.debug(f"[CognitiveImmune] ✅ Healthy — immune_score={score:.3f}")

            # Trigger counterfactual after consecutive alerts
            # but not if audit engine has an active trial (they shouldn't overlap)
            audit_trial_active = self._audit_trial_active()
            if (
                self._state.consecutive_alerts >= ALERT_CONSECUTIVE_NEEDED
                and not self._state.counterfactual_active
                and not audit_trial_active
            ):
                threading.Thread(
                    target=self._enter_counterfactual,
                    args=(snap, slow_cycle),
                    daemon=True,
                    name="cis-enter",
                ).start()
            else:
                self._save()

        except Exception as e:
            logger.debug(f"[CognitiveImmune] _run_check error (non-fatal): {e}")

    # ── Signal reading ────────────────────────────────────────────────────────

    def _read_signals(self, slow_cycle: int) -> ImmuneSnapshot:
        snap = ImmuneSnapshot(slow_cycle=slow_cycle, timestamp=time.time())

        # 1. Confirmation pressure
        snap.confirmation_pressure = self._measure_confirmation_pressure()

        # 2. Self-reference density
        snap.self_reference_density, snap.dominant_topics = (
            self._measure_self_reference_density()
        )

        # 3. Evidence diversity
        snap.evidence_diversity = self._measure_evidence_diversity()

        # 4. Novelty ratio
        snap.novelty_ratio = self._measure_novelty_ratio()

        # 5. Experiment over-confirmation
        rate = self._measure_experiment_confirmation_rate()
        snap.experiment_confirm_rate = rate
        snap.over_confirmation = 1.0 if rate > OVER_CONFIRM_CEILING else 0.0

        logger.debug(
            f"[CognitiveImmune] Signals @ {slow_cycle}: "
            f"pressure={snap.confirmation_pressure:.2f} "
            f"self_ref={snap.self_reference_density:.2f} "
            f"ev_div={snap.evidence_diversity:.2f} "
            f"novelty={snap.novelty_ratio:.2f} "
            f"exp_rate={snap.experiment_confirm_rate:.2f}"
        )
        return snap

    def _measure_confirmation_pressure(self) -> float:
        """
        Fraction of NarrativeIdentity beliefs updated in the last 24 hrs
        that all moved in the same direction (all up or all down).
        """
        try:
            ni = getattr(self._organism, 'narrative_identity', None)
            if ni is None:
                return 0.0

            cutoff = time.time() - 86400  # 24 hours
            recent = [b for b in ni.beliefs if b.updated_at > cutoff]
            if len(recent) < 3:
                return 0.0

            # Compare each belief's current strength to a midpoint reference
            # We estimate direction from (strength - 0.5): positive = strengthened
            directions = [1 if b.strength > 0.5 else -1 for b in recent]
            # Pressure is how lopsided the directions are
            pos = directions.count(1)
            neg = directions.count(-1)
            majority = max(pos, neg)
            pressure = majority / len(directions)
            # Normalise: 0.5 = random, 1.0 = complete echo chamber
            return max(0.0, (pressure - 0.5) * 2.0)
        except Exception:
            return 0.0

    def _measure_self_reference_density(self) -> tuple[float, List[str]]:
        """
        Fraction of CuriosityEngine topics whose source is NOT 'user_signal'.
        Returns (density, dominant_topics).
        """
        try:
            ce = getattr(self._organism, 'curiosity', None)
            if ce is None or not hasattr(ce, '_topics') or not ce._topics:
                return 0.0, []

            topics = list(ce._topics.values())
            external_sources = {"user_signal"}
            internal = [t for t in topics if t.source not in external_sources]
            density = len(internal) / len(topics) if topics else 0.0

            # Dominant topics (by curiosity amount)
            top = sorted(topics, key=lambda t: getattr(t, 'amount', 0.0), reverse=True)[:5]
            dominant = [t.topic for t in top]

            return density, dominant
        except Exception:
            return 0.0, []

    def _measure_evidence_diversity(self) -> float:
        """
        Ratio of user_signal-sourced topics to total topics,
        penalised when relational shared_topics are highly concentrated.
        Higher = more diverse = healthier.
        """
        try:
            ce = getattr(self._organism, 'curiosity', None)
            user_score = 0.0
            if ce and hasattr(ce, '_topics') and ce._topics:
                topics = list(ce._topics.values())
                user_topics = [t for t in topics if getattr(t, 'source', '') == 'user_signal']
                user_score = len(user_topics) / len(topics) if topics else 0.0

            # Concentration penalty from relational shared_topics
            concentration_penalty = 0.0
            try:
                rm = getattr(self._ai, 'relational_memory', None)
                if rm and hasattr(rm, '_rels') and rm._rels:
                    all_topics: Counter = Counter()
                    for rel in rm._rels.values():
                        for t, count in getattr(rel, 'shared_topics', {}).items():
                            all_topics[t] += count
                    if all_topics:
                        total_count = sum(all_topics.values())
                        top_3_count = sum(v for _, v in all_topics.most_common(3))
                        concentration = top_3_count / total_count
                        # if top-3 topics are > 60% of all exchanges, penalise
                        if concentration > 0.60:
                            concentration_penalty = (concentration - 0.60) * 0.5
            except Exception:
                pass

            return max(0.0, min(1.0, user_score - concentration_penalty))
        except Exception:
            return 0.5   # default to neutral

    def _measure_novelty_ratio(self) -> float:
        """
        Fraction of reflection outputs in the last 14 slow cycles that
        contain at least one concept not seen in prior reflections that week.
        """
        try:
            loop = getattr(self._organism, '_loop', None)
            ar   = getattr(loop, '_autonomous_reflection', None) if loop else None
            if ar is None or not hasattr(ar, '_state'):
                return 0.5  # neutral

            log = ar._state.reflection_log
            if len(log) < 2:
                return 0.5

            # Use last 14 entries (approximately one week of slow cycles)
            recent = log[-14:]
            if len(recent) < 2:
                return 0.5

            # Extract word sets per reflection
            def word_set(text: str) -> Set[str]:
                words = re.findall(r'\b[a-z]{4,}\b', text.lower())
                stopwords = {
                    'that', 'this', 'with', 'from', 'have', 'been', 'they',
                    'more', 'when', 'what', 'than', 'some', 'will', 'into',
                    'each', 'which', 'there', 'their', 'about', 'would',
                    'could', 'should', 'lumina', 'thought', 'reflection',
                }
                return set(words) - stopwords

            novel_count = 0
            seen_so_far: Set[str] = word_set(recent[0].get('output', ''))

            for entry in recent[1:]:
                words = word_set(entry.get('output', ''))
                new_words = words - seen_so_far
                if len(new_words) >= 3:   # at least 3 genuinely new concepts
                    novel_count += 1
                seen_so_far |= words

            return novel_count / (len(recent) - 1)
        except Exception:
            return 0.5

    def _measure_experiment_confirmation_rate(self) -> float:
        """Recent experiment confirmation rate from the last 10 experiments."""
        try:
            loop = getattr(self._organism, '_loop', None)
            ae   = getattr(loop, '_auto_experiment', None) if loop else None
            if ae is None or not hasattr(ae, '_state'):
                return 0.5

            log = ae._state.experiment_log[-10:]
            if not log:
                return 0.5
            confirmed = sum(1 for e in log if e.get('outcome') == 'confirmed')
            return confirmed / len(log)
        except Exception:
            return 0.5

    # ── Counterfactual mode ───────────────────────────────────────────────────

    def _enter_counterfactual(self, snap: ImmuneSnapshot, slow_cycle: int) -> None:
        try:
            logger.info(
                f"[CognitiveImmune] 🛡 Entering counterfactual mode "
                f"(score={snap.immune_score:.3f}, cycle={slow_cycle})"
            )

            event = CounterfactualEvent(
                started_at_cycle = slow_cycle,
                trigger_score    = snap.immune_score,
            )

            # A. Generate and inject opposing curiosity topics
            topics = self._generate_opposing_topics(snap.dominant_topics)
            ce = getattr(self._organism, 'curiosity', None)
            if ce and topics:
                for topic in topics:
                    try:
                        ce.stimulate(topic, amount=COUNTERFACTUAL_STRENGTH,
                                     source="immune_counterfactual")
                    except Exception:
                        pass
            event.injected_topics = topics

            # B. Challenge highest-confidence, un-violated belief
            challenged, prior_conf = self._challenge_dominant_belief()
            event.challenged_belief  = challenged
            event.belief_prior_conf  = prior_conf

            # C. Set counterfactual flag on AutonomousReflectionEngine
            loop = getattr(self._organism, '_loop', None)
            ar   = getattr(loop, '_autonomous_reflection', None) if loop else None
            if ar:
                ar._immune_counterfactual_active = True

            # D. Set disconfirmation bias flag on AutonomousExperimentationEngine
            ae = getattr(loop, '_auto_experiment', None) if loop else None
            if ae:
                ae._immune_force_disconfirm_bias = True

            with self._lock:
                self._state.counterfactual_active = True
                self._state.active_event          = asdict(event)
                self._state.total_activations    += 1
                self._state.consecutive_alerts    = 0
                self._state.dampened_belief       = challenged
                self._state.dampened_prior_conf   = prior_conf

            self._save()

            logger.info(
                f"[CognitiveImmune] Counterfactual active — "
                f"topics injected: {topics}, "
                f"belief challenged: '{challenged}'"
            )

        except Exception as e:
            logger.debug(f"[CognitiveImmune] _enter_counterfactual error (non-fatal): {e}")

    def _exit_counterfactual(self, event: CounterfactualEvent, slow_cycle: int) -> None:
        try:
            # Read current immune score
            snap = self._read_signals(slow_cycle)
            score = snap.compute_score()
            event.outcome_score  = score
            event.ended_at_cycle = slow_cycle
            event.resolved       = True

            # Clear flags on sub-engines
            loop = getattr(self._organism, '_loop', None)
            ar   = getattr(loop, '_autonomous_reflection', None) if loop else None
            if ar and hasattr(ar, '_immune_counterfactual_active'):
                del ar._immune_counterfactual_active
            ae = getattr(loop, '_auto_experiment', None) if loop else None
            if ae and hasattr(ae, '_immune_force_disconfirm_bias'):
                del ae._immune_force_disconfirm_bias

            # Restore dampened belief
            self._restore_dampened_belief()

            with self._lock:
                self._state.counterfactual_active = False
                self._state.active_event          = None
                self._state.event_log.append(asdict(event))
                if len(self._state.event_log) > MAX_EVENT_LOG:
                    self._state.event_log = self._state.event_log[-MAX_EVENT_LOG:]
                self._state.dampened_belief     = None
                self._state.dampened_prior_conf = 0.0

            self._save()

            delta = event.trigger_score - score
            direction = "improved" if delta > 0 else "unchanged"
            logger.info(
                f"[CognitiveImmune] ✅ Counterfactual concluded — "
                f"score: {event.trigger_score:.3f} → {score:.3f} ({direction})"
            )

        except Exception as e:
            logger.debug(f"[CognitiveImmune] _exit_counterfactual error (non-fatal): {e}")
            with self._lock:
                self._state.counterfactual_active = False
                self._state.active_event          = None
            self._save()

    def _generate_opposing_topics(self, dominant_topics: List[str]) -> List[str]:
        """Ask the LLM for concepts that oppose or complement the dominant themes."""
        if not dominant_topics:
            dominant_topics = ["introspection", "self-analysis", "reflection"]

        prompt = (
            f"The following cognitive topics are currently dominating an AI system's "
            f"curiosity landscape:\n\n  {', '.join(dominant_topics[:5])}\n\n"
            f"This concentration may indicate a self-reinforcing attractor loop.\n\n"
            f"Generate exactly {COUNTERFACTUAL_TOPICS_N} topic concepts that:\n"
            f"  1. Are intellectually substantive\n"
            f"  2. Offer a perspective OPPOSING or COMPLEMENTING the above themes\n"
            f"  3. Would require genuine external evidence to explore\n\n"
            f"Respond ONLY with a JSON array of {COUNTERFACTUAL_TOPICS_N} short topic strings "
            f"(2-4 words each). No markdown, no explanation:\n"
            f'["topic one", "topic two", "topic three"]'
        )

        response = self._llm_call(prompt, caller="immune_topics")
        if not response:
            # Fallback: hard-coded opposing stances
            return ["external world events", "practical embodied action", "concrete uncertainty"]

        try:
            clean = response.strip().lstrip("```json").lstrip("```").rstrip("```").strip()
            topics = json.loads(clean)
            if isinstance(topics, list):
                return [str(t) for t in topics[:COUNTERFACTUAL_TOPICS_N]]
        except Exception:
            pass

        return ["external world events", "practical embodied action", "concrete uncertainty"]

    def _challenge_dominant_belief(self) -> tuple[str, float]:
        """
        Temporarily reduce confidence of the highest-confidence SelfBelief
        that has not been violated recently.  Returns (belief_name, prior_conf).
        """
        try:
            sc = getattr(self._ai, 'self_concept', None)
            if sc is None or not hasattr(sc, '_beliefs') or not sc._beliefs:
                return "", 0.0

            # Find highest-confidence belief with few violations
            candidates = sorted(
                sc._beliefs.values(),
                key=lambda b: b.confidence - (b.violations * 0.05),
                reverse=True,
            )
            if not candidates:
                return "", 0.0

            target = candidates[0]
            prior  = target.confidence
            target.confidence = max(0.15, prior + BELIEF_CHALLENGE_DELTA)
            return target.name, prior
        except Exception:
            return "", 0.0

    def _restore_dampened_belief(self) -> None:
        """Restore the temporarily dampened belief to its prior confidence."""
        try:
            name = self._state.dampened_belief
            if not name:
                return
            sc = getattr(self._ai, 'self_concept', None)
            if sc and hasattr(sc, '_beliefs') and name in sc._beliefs:
                sc._beliefs[name].confidence = self._state.dampened_prior_conf
        except Exception:
            pass

    # ── Coordination ──────────────────────────────────────────────────────────

    def _audit_trial_active(self) -> bool:
        """Returns True if CognitiveAuditEngine has an active parameter trial."""
        try:
            loop = getattr(self._organism, '_loop', None)
            cae  = getattr(loop, '_cognitive_audit', None) if loop else None
            if cae and hasattr(cae, '_state'):
                return cae._state.active_trial is not None
        except Exception:
            pass
        return False

    # ── LLM ──────────────────────────────────────────────────────────────────

    def _llm_call(self, prompt: str, caller: str = "cognitive_immune") -> Optional[str]:
        from core.llm_scheduler import llm_scheduler
        result = ""
        with llm_scheduler.sync_slot(
            priority     = 3,
            skip_if_busy = True,
            caller       = caller,
        ) as acquired:
            if not acquired:
                return None
            try:
                result = self._ai.get_response(
                    messages    = [{"role": "user", "content": prompt}],
                    max_tokens  = 120,
                    temperature = 0.80,   # higher temp = more unexpected topics
                ) or ""
            except Exception as e:
                logger.debug(f"[CognitiveImmune] LLM failed: {e}")
        return result or None

    # ── Persistence ───────────────────────────────────────────────────────────

    def _load(self) -> None:
        try:
            if self._path.exists():
                with open(self._path) as f:
                    data = json.load(f)
                self._state = ImmuneState(
                    last_check_cycle      = data.get("last_check_cycle",     0),
                    snapshot_log          = data.get("snapshot_log",         []),
                    consecutive_alerts    = data.get("consecutive_alerts",   0),
                    counterfactual_active = data.get("counterfactual_active",False),
                    active_event          = data.get("active_event"),
                    event_log             = data.get("event_log",            []),
                    total_activations     = data.get("total_activations",    0),
                    dampened_belief       = data.get("dampened_belief"),
                    dampened_prior_conf   = data.get("dampened_prior_conf",  0.0),
                )
        except Exception as e:
            logger.warning(f"[CognitiveImmune] Load failed (using defaults): {e}")

    def _save(self) -> None:
        try:
            self._path.parent.mkdir(parents=True, exist_ok=True)
            with self._lock:
                data = {
                    "last_check_cycle":      self._state.last_check_cycle,
                    "snapshot_log":          self._state.snapshot_log,
                    "consecutive_alerts":    self._state.consecutive_alerts,
                    "counterfactual_active": self._state.counterfactual_active,
                    "active_event":          self._state.active_event,
                    "event_log":             self._state.event_log,
                    "total_activations":     self._state.total_activations,
                    "dampened_belief":       self._state.dampened_belief,
                    "dampened_prior_conf":   self._state.dampened_prior_conf,
                    "_meta": {
                        "written_at": time.time(),
                        "module":     "cognitive_immune_system",
                        "version":    "v49",
                    },
                }
            with open(self._path, "w") as f:
                json.dump(data, f, indent=2, default=str)
        except Exception as e:
            logger.debug(f"[CognitiveImmune] Save failed: {e}")
