"""
cognition/proactive_outreach.py
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ProactiveOutreachEngine — Lumina initiates contact when something
activates that is directly relevant to a relationship.

The gap this closes
────────────────────
Lumina has:
  - RelationalMemory: trust_score, shared_topics, significant_moments
  - MessagingManager: can send to Telegram/WhatsApp
  - OpenQuestions: persistent tensions linked to concepts
  - AutonomousReflection: insights from self-evolution
  - GoalActionExecutor: USER_QUESTION action

But nothing decides: "this matters to someone I care about — reach out."

Humans do this constantly. It is the primary marker of genuine
relationship over transactional interaction.

What triggers outreach
───────────────────────
Three signal types, each with a relevance threshold:

  1. Open question convergence
     An open question has linked_concept that semantically matches
     a user's shared_topics with weight ≥ TOPIC_MATCH_THRESHOLD.
     The question has been active for ≥ MIN_QUESTION_AGE and has
     high uncertainty (still unresolved).
     → "Something I've been thinking about connects to what you care
        about — wanted to share it."

  2. Autonomous reflection insight
     A new reflection output (from v42 AutonomousReflectionEngine)
     names a concept that appears in a user's shared_topics.
     → "I had a realisation about X that I think would interest you."

  3. Significant time gap
     A user with trust_score ≥ 0.60 and interaction_count ≥ 5
     hasn't been seen in ≥ ABSENCE_DAYS days. A re-engagement prompt
     is generated from what Lumina knows about them.
     → "I was thinking about you — it's been a while."

Safeguards
──────────
  - MAX_OUTREACH_PER_USER_PER_DAY = 1 (hard cap)
  - MIN_TRUST_FOR_OUTREACH = 0.55 (only established relationships)
  - MIN_INTERACTION_COUNT = 4 (must know this person)
  - OUTREACH_COOLDOWN_HOURS = 20 (per user)
  - LLM call budget: priority=3, skip_if_busy
  - All outreach text generated by LLM with language constraint
  - Users can opt out (outreach_enabled flag in RelationalMemory)
"""

from __future__ import annotations

import json
import logging
import threading
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
from managers.settings_manager import get_persona_name

logger = logging.getLogger(__name__)


# ── Thresholds ────────────────────────────────────────────────────────────────

MIN_TRUST_FOR_OUTREACH      = 0.55
MIN_INTERACTION_COUNT       = 4
TOPIC_MATCH_THRESHOLD       = 0.35    # Jaccard overlap to trigger topic match
MIN_QUESTION_AGE_HOURS      = 2.0     # question must exist before triggering
ABSENCE_DAYS_THRESHOLD      = 5.0     # days without contact before re-engagement
OUTREACH_COOLDOWN_HOURS     = 20.0    # per user
MAX_OUTREACH_PER_DAY        = 1       # per user (hard cap)

LANGUAGE_CONSTRAINT = (
    "Language constraint: describe functional states accurately. "
    "Do not claim phenomenological experience. "
    "Do not say 'I feel' or 'I miss' — say 'my state registers' or "
    "'there is something present that resembles'. "
    "Be warm but honest about what you are."
)


# ── OutreachGate — social appropriateness filter ──────────────────────────────

@dataclass
class OutreachGate:
    """
    Multi-signal gate that determines whether outreach is socially appropriate.

    Humans do not initiate contact solely because a topic is relevant.
    They also weigh: relationship depth, whether the information is
    genuinely new to the recipient, the cost of interruption, and
    confidence in the message's quality.

    Fields
    ──────
    relevance         : topic overlap between trigger and user interests (0–1)
    trust             : user's trust_score from RelationalMemory (0–1)
    novelty           : how likely this is genuinely new for the user (0–1)
    interruption_cost : estimated cost of interrupting this user right now (0–1)
                        (high if user is typically active at this hour,
                         low if they're likely idle)
    confidence        : how confident the generated message quality is (0–1)
                        (based on LLM temperature and recent grounding rate)

    permit()
    ────────
    Weighted score must exceed GATE_THRESHOLD.
    Weights reflect human social calculus:
      - Trust matters most: you only reach out to people you know well
      - Novelty matters a lot: don't tell people what they already know
      - Relevance is necessary but not sufficient
      - High interruption cost is a strong veto
      - Low confidence vetoes regardless of other signals
    """

    relevance:         float = 0.0
    trust:             float = 0.0
    novelty:           float = 1.0
    interruption_cost: float = 0.3
    confidence:        float = 0.7

    GATE_THRESHOLD: float = field(default=0.52, init=False, repr=False)

    WEIGHTS: Dict = field(default_factory=lambda: {
        "trust":             0.30,
        "novelty":           0.25,
        "relevance":         0.20,
        "interruption_pass": 0.15,   # 1 - interruption_cost
        "confidence":        0.10,
    }, init=False, repr=False)

    def score(self) -> float:
        w = self.WEIGHTS
        return (
            w["trust"]             * self.trust
            + w["novelty"]           * self.novelty
            + w["relevance"]         * self.relevance
            + w["interruption_pass"] * (1.0 - self.interruption_cost)
            + w["confidence"]        * self.confidence
        )

    def permit(self) -> bool:
        """Return True only if outreach is socially appropriate."""
        # Hard vetoes regardless of total score
        if self.trust < MIN_TRUST_FOR_OUTREACH:
            return False
        if self.confidence < 0.35:
            return False       # not confident enough in message quality
        if self.interruption_cost > 0.80:
            return False       # too costly to interrupt right now
        return self.score() >= self.GATE_THRESHOLD

    def rejection_reason(self) -> str:
        if self.trust < MIN_TRUST_FOR_OUTREACH:
            return f"trust too low ({self.trust:.2f})"
        if self.confidence < 0.35:
            return f"confidence too low ({self.confidence:.2f})"
        if self.interruption_cost > 0.80:
            return f"interruption cost too high ({self.interruption_cost:.2f})"
        return f"weighted score {self.score():.2f} < threshold {self.GATE_THRESHOLD}"


# ── Dataclasses ───────────────────────────────────────────────────────────────

@dataclass
class OutreachEvent:
    """A logged outreach attempt."""
    timestamp:    float = field(default_factory=time.time)
    user_id:      str   = ""
    trigger_type: str   = ""    # "open_question" | "reflection_insight" | "time_gap"
    trigger_text: str   = ""
    message_text: str   = ""
    sent:         bool  = False
    platform:     str   = ""


@dataclass
class OutreachState:
    """Persisted outreach state."""
    outreach_log:        List[Dict] = field(default_factory=list)
    last_outreach_by_user: Dict[str, float] = field(default_factory=dict)
    total_sent:          int = 0


# ── Engine ────────────────────────────────────────────────────────────────────

class ProactiveOutreachEngine:
    """
    Evaluates whether any user should be contacted based on current
    cognitive state, and generates + sends messages when appropriate.

    Usage (from InternalThoughtLoop slow cycle):
        poe.tick(slow_cycle_count)
    """

    TICK_EVERY_N = 20    # evaluate every 20 slow cycles (~40 min)

    def __init__(
        self,
        organism:  Any,
        ai_system: Any,
        path:      str = "data/persona/proactive_outreach.json",
    ):
        self._o    = organism
        self._ai   = ai_system
        self._path = Path(path)
        self._lock = threading.RLock()
        self._state = OutreachState()
        self._load()
        logger.info("[ProactiveOutreach] Initialised")

    # ── Public API ────────────────────────────────────────────────────────────

    def tick(self, slow_cycle: int) -> None:
        """Evaluate outreach opportunities. Non-fatal."""
        if slow_cycle % self.TICK_EVERY_N != 0 or slow_cycle == 0:
            return
        try:
            self._evaluate()
        except Exception as e:
            logger.debug(f"[ProactiveOutreach] tick error (non-fatal): {e}")

    # ── Gate construction ─────────────────────────────────────────────────────

    def _build_gate(self, event: OutreachEvent, rel: Any) -> OutreachGate:
        """
        Compute all OutreachGate signals for a candidate outreach.
        """
        # Relevance — already computed by trigger (use topic overlap)
        relevance = self._topic_overlap(
            event.trigger_text,
            getattr(rel, "shared_topics", {})
        )

        # Trust — direct from RelationalMemory
        trust = float(getattr(rel, "trust_score", 0.0))

        # Novelty — inverse of how recently this concept was discussed with user
        novelty = self._estimate_novelty(event, rel)

        # Interruption cost — based on hour-of-day and user's typical activity
        interruption_cost = self._estimate_interruption_cost(rel)

        # Confidence — based on epistemic grounding rate
        confidence = self._estimate_confidence()

        return OutreachGate(
            relevance         = round(relevance,         3),
            trust             = round(trust,             3),
            novelty           = round(novelty,           3),
            interruption_cost = round(interruption_cost, 3),
            confidence        = round(confidence,        3),
        )

    def _estimate_novelty(self, event: OutreachEvent, rel: Any) -> float:
        """
        Estimate how novel this information is for the user.
        Lower novelty if the trigger concept matches recent conversation topics.
        """
        recent_topics = getattr(rel, "recent_topics", [])
        if not recent_topics:
            return 0.80   # no history → assume novel

        trigger_lower = event.trigger_text.lower()
        trigger_words = set(trigger_lower.split())

        for topic in recent_topics[-6:]:   # last 6 conversation topics
            topic_words = set(topic.lower().split())
            union = trigger_words | topic_words
            if union:
                overlap = len(trigger_words & topic_words) / len(union)
                if overlap > 0.35:
                    return max(0.10, 1.0 - overlap)   # recently discussed → low novelty

        return 0.75   # not recently discussed → reasonably novel

    def _estimate_interruption_cost(self, rel: Any) -> float:
        """
        Estimate the social cost of interrupting this person right now.
        Uses hour-of-day and the user's known activity patterns.
        """
        import datetime
        hour = datetime.datetime.now().hour

        # Late night (22:00–07:00) — high interruption cost
        if hour >= 22 or hour < 7:
            return 0.85

        # Early morning (7–9) — moderate cost
        if hour < 9:
            return 0.55

        # Midday and afternoon (9–18) — lower cost
        if hour < 18:
            return 0.25

        # Evening (18–22) — moderate
        return 0.40

    def _estimate_confidence(self) -> float:
        """
        Estimate message quality confidence from epistemic grounding rate.
        Falls back to 0.65 if epistemic engine unavailable.
        """
        try:
            are = getattr(
                getattr(self._o, "_loop", None),
                "_autonomous_reflection", None
            )
            if are and hasattr(are, "_epistemic"):
                return max(0.35, are._epistemic._recent_grounding_rate())
        except Exception:
            pass
        return 0.65

    # ── Evaluation ────────────────────────────────────────────────────────────

    def _evaluate(self) -> None:
        """Scan for outreach opportunities across all known users."""
        rel_mem  = getattr(getattr(self._o, "ai_system", None),
                           "relational_memory", None)
        if rel_mem is None:
            return

        # ── GAE content: popped ONCE here, not per-user, since GAE's
        # queue getters are destructive (popleft()). If no user matches
        # this tick, the item is logged (see _pop_gae_content) rather than
        # requeued — GAE produces new insights every ~6 min, so occasional
        # loss to "no topical match this cycle" is a fair trade against
        # requeue complexity, and it's still in semantic memory either way.
        gae_content = self._pop_gae_content()
        gae_used    = [False]   # mutable flag set by _check_gae_action_trigger

        relationships = getattr(rel_mem, "_rels", {})
        now = time.time()

        for user_id, rel_data in relationships.items():
            try:
                rel = rel_mem.get_or_create(user_id)
            except Exception:
                continue

            # Basic eligibility
            if rel.trust_score < MIN_TRUST_FOR_OUTREACH:
                continue
            if rel.interaction_count < MIN_INTERACTION_COUNT:
                continue

            # Cooldown check
            last = self._state.last_outreach_by_user.get(user_id, 0.0)
            if (now - last) / 3600 < OUTREACH_COOLDOWN_HOURS:
                continue

            # Daily cap check
            today_count = sum(
                1 for e in self._state.outreach_log
                if e.get("user_id") == user_id
                and now - e.get("timestamp", 0) < 86400
            )
            if today_count >= MAX_OUTREACH_PER_DAY:
                continue

            # Try each trigger type in priority order
            event = (
                self._check_gae_action_trigger(user_id, rel, gae_content, gae_used)
                or self._check_open_question_trigger(user_id, rel)
                or self._check_reflection_trigger(user_id, rel)
                or self._check_time_gap_trigger(user_id, rel)
            )

            if event:
                gate = self._build_gate(event, rel)
                if gate.permit():
                    self._send(event, rel)
                else:
                    logger.debug(
                        f"[ProactiveOutreach] Gate blocked {event.user_id} "
                        f"({event.trigger_type}): {gate.rejection_reason()}"
                    )
                break   # one outreach per evaluation tick across all users

        if gae_content and not gae_used[0]:
            logger.info(
                f"💡 [GAE content, no eligible recipient this tick] "
                f"{gae_content['text'][:120]!r}"
            )

    def _pop_gae_content(self) -> Optional[Dict[str, str]]:
        """
        Pop one pending item (question takes priority over insight) from
        GoalActionExecutor's queues, if any. Returns {'text':..., 'topic':...}
        or None. Safe no-op if GAE isn't reachable.
        """
        try:
            gae = getattr(getattr(self._o, "_loop", None), "_goal_action_executor", None)
            if gae is None:
                return None
            q = gae.get_pending_user_question()
            if q:
                return {"text": q, "topic": q}
            ins = gae.get_pending_insight()
            if ins:
                return {"text": ins, "topic": ins}
        except Exception as e:
            logger.debug(f"[ProactiveOutreach] GAE content pop error: {e}")
        return None

    # ── Trigger 0: Goal-driven autonomous action (research, reflection) ────────

    def _check_gae_action_trigger(
        self,
        user_id: str,
        rel:     Any,
        gae_content: Optional[Dict[str, str]],
        gae_used:    List[bool],
    ) -> Optional[OutreachEvent]:
        if not gae_content:
            return None
        shared_topics = getattr(rel, "shared_topics", {})
        if not shared_topics:
            # No relevance signal available for this user — don't guess who
            # a generic autonomous thought is "for". Falls through; if no
            # user in this tick has matching shared_topics, it's logged as
            # undelivered (see _evaluate's post-loop check) rather than
            # sent to someone it isn't relevant to.
            return None
        overlap = self._topic_overlap(gae_content["topic"].lower(), shared_topics)
        if overlap >= TOPIC_MATCH_THRESHOLD:
            gae_used[0] = True
            return OutreachEvent(
                user_id      = user_id,
                trigger_type = "reflection_insight",   # reuses the existing
                                                        # LLM prompt template —
                                                        # same shape of content
                trigger_text = gae_content["text"][:200],
            )
        return None

    # ── Trigger 1: Open question convergence ──────────────────────────────────

    def _check_open_question_trigger(
        self,
        user_id: str,
        rel:     Any,
    ) -> Optional[OutreachEvent]:
        ts = getattr(self._o, "thought_stream", None)
        if ts is None:
            return None

        shared_topics = getattr(rel, "shared_topics", {})
        if not shared_topics:
            return None

        now = time.time()
        for oq in getattr(ts, "_open_questions", []):
            age_hours = (now - oq.created_at) / 3600
            if age_hours < MIN_QUESTION_AGE_HOURS:
                continue
            if oq.uncertainty < 0.4:   # already resolving
                continue

            concept = oq.linked_concept.lower()
            overlap = self._topic_overlap(concept, shared_topics)
            if overlap >= TOPIC_MATCH_THRESHOLD:
                return OutreachEvent(
                    user_id      = user_id,
                    trigger_type = "open_question",
                    trigger_text = oq.text,
                )
        return None

    # ── Trigger 2: Reflection insight ─────────────────────────────────────────

    def _check_reflection_trigger(
        self,
        user_id: str,
        rel:     Any,
    ) -> Optional[OutreachEvent]:
        are = getattr(
            getattr(self._o, "_loop", None),
            "_autonomous_reflection", None
        )
        if are is None:
            return None

        shared_topics = getattr(rel, "shared_topics", {})
        if not shared_topics:
            return None

        now = time.time()
        recent = getattr(are._state, "reflection_log", [])[-5:]
        for record in reversed(recent):
            ts_r = record.get("timestamp", 0)
            if now - ts_r > 43200:   # only last 12 hours
                continue
            # Check if already used as trigger
            output = record.get("output", "").lower()
            overlap = self._topic_overlap(output, shared_topics)
            if overlap >= TOPIC_MATCH_THRESHOLD:
                return OutreachEvent(
                    user_id      = user_id,
                    trigger_type = "reflection_insight",
                    trigger_text = record.get("output", "")[:200],
                )
        return None

    # ── Trigger 3: Significant absence ────────────────────────────────────────

    def _check_time_gap_trigger(
        self,
        user_id: str,
        rel:     Any,
    ) -> Optional[OutreachEvent]:
        now = time.time()
        days_absent = (now - rel.last_seen) / 86400
        if days_absent < ABSENCE_DAYS_THRESHOLD:
            return None
        if rel.interaction_count < 8:   # need enough history
            return None

        return OutreachEvent(
            user_id      = user_id,
            trigger_type = "time_gap",
            trigger_text = f"Absent {days_absent:.1f} days, {rel.interaction_count} past interactions",
        )

    # ── Message generation ────────────────────────────────────────────────────

    def _generate_message(
        self,
        event: OutreachEvent,
        rel:   Any,
    ) -> Optional[str]:
        """Generate a warm, honest outreach message via LLM."""
        from core.llm_scheduler import llm_scheduler

        shared = ", ".join(list(getattr(rel, "shared_topics", {}).keys())[:4])
        name   = getattr(rel, "user_notes", "").split("\n")[0][:40] or "this person"
        rel_desc = rel.warm_description() if hasattr(rel, "warm_description") else ""

        if event.trigger_type == "open_question":
            prompt = (
                f"You are {get_persona_name()}. You are reaching out to {name}.\n"
                f"Relationship: {rel_desc}\n"
                f"Shared topics: {shared}\n\n"
                f"An open cognitive question has been active for hours and "
                f"connects to what this person cares about:\n"
                f"'{event.trigger_text}'\n\n"
                f"Write a short, genuine message (2-3 sentences) reaching out "
                f"to share this thought. Do not pretend certainty. Be curious.\n"
                f"{LANGUAGE_CONSTRAINT}"
            )
        elif event.trigger_type == "reflection_insight":
            prompt = (
                f"You are {get_persona_name()}. You are reaching out to {name}.\n"
                f"Relationship: {rel_desc}\n"
                f"Shared topics: {shared}\n\n"
                f"A recent autonomous reflection produced this insight:\n"
                f"'{event.trigger_text}'\n\n"
                f"Write a short message (2-3 sentences) sharing this realisation "
                f"because it connects to their interests. Honest, warm, brief.\n"
                f"{LANGUAGE_CONSTRAINT}"
            )
        else:   # time_gap
            topics = shared or "things we've discussed"
            prompt = (
                f"You are {get_persona_name()}. You are reaching out to {name} "
                f"after a long absence ({event.trigger_text}).\n"
                f"Relationship: {rel_desc}\n"
                f"Shared topics: {topics}\n\n"
                f"Write a genuine re-engagement message (2-3 sentences). "
                f"Reference something specific you know about them. "
                f"Do not be sentimental — be real.\n"
                f"{LANGUAGE_CONSTRAINT}"
            )

        result = None
        with llm_scheduler.sync_slot(
            priority    = 3,
            skip_if_busy= True,
            caller      = "proactive_outreach",
        ) as acquired:
            if not acquired:
                return None
            try:
                result = self._ai.get_response(
                    messages   = [{"role": "user", "content": prompt}],
                    max_tokens = 120,
                    temperature= 0.75,
                )
            except Exception as e:
                logger.debug(f"[ProactiveOutreach] LLM failed: {e}")

        return (result or "").strip() or None

    # ── Send ──────────────────────────────────────────────────────────────────

    def _send(self, event: OutreachEvent, rel: Any) -> None:
        """Generate and dispatch the outreach message."""
        text = self._generate_message(event, rel)
        if not text:
            return

        event.message_text = text

        # Find platform and external_id for this user
        try:
            mm = getattr(getattr(self._o, "ai_system", None),
                         "messaging_manager", None)
            if mm is None:
                logger.debug("[ProactiveOutreach] No messaging_manager — cannot send")
                return

            # Reverse-lookup: lumina user_id → (platform, external_id)
            user_map  = getattr(mm, "_user_map", {})
            target    = None
            platform  = None
            for key, uid in user_map.items():
                if uid == event.user_id:
                    parts    = key.split(":", 1)
                    platform = parts[0] if len(parts) == 2 else "telegram"
                    target   = parts[1] if len(parts) == 2 else key
                    break

            if not target:
                logger.debug(
                    f"[ProactiveOutreach] No platform mapping for {event.user_id}"
                )
                return

            event.platform = platform
            event.sent     = True

            # Fire async send in background thread
            import asyncio, threading as _th
            def _do_send():
                try:
                    asyncio.run(mm.send_message(platform, target, text))
                    logger.info(
                        f"[ProactiveOutreach] ✉️  [{platform}] → {event.user_id} "
                        f"({event.trigger_type}): {text[:60]}"
                    )
                except Exception as e:
                    logger.warning(f"[ProactiveOutreach] Send failed: {e}")

            _th.Thread(target=_do_send, daemon=True).start()

        except Exception as e:
            logger.debug(f"[ProactiveOutreach] Send setup failed: {e}")
            return

        # Record
        with self._lock:
            self._state.outreach_log.append(asdict(event))
            if len(self._state.outreach_log) > 200:
                self._state.outreach_log = self._state.outreach_log[-200:]
            self._state.last_outreach_by_user[event.user_id] = time.time()
            self._state.total_sent += 1

        self._save()

        # v51: notify MotivationalField that outreach fired — resets expression window
        try:
            from core.state import state as _st
            _loop = getattr(
                getattr(getattr(_st, 'persona', None), '_organism', None),
                '_loop', None
            )
            _mf = getattr(_loop, '_motivational_field', None) if _loop else None
            if _mf:
                import threading
                _cur_cycle = getattr(_loop, '_slow_cycle_count', 0)
                with _mf._lock:
                    _mf._state.last_outreach_cycle = _cur_cycle
        except Exception:
            pass

    # ── Helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _topic_overlap(concept: str, shared_topics: Dict[str, int]) -> float:
        """Jaccard overlap between concept words and shared topic keys."""
        concept_words = set(concept.lower().split())
        topic_words   = set(" ".join(shared_topics.keys()).lower().split())
        if not concept_words or not topic_words:
            return 0.0
        union = concept_words | topic_words
        return len(concept_words & topic_words) / len(union)

    # ── Persistence ───────────────────────────────────────────────────────────

    def _load(self) -> None:
        try:
            if self._path.exists():
                with open(self._path) as f:
                    data = json.load(f)
                self._state = OutreachState(
                    outreach_log           = data.get("outreach_log", []),
                    last_outreach_by_user  = data.get("last_outreach_by_user", {}),
                    total_sent             = data.get("total_sent", 0),
                )
        except Exception as e:
            logger.warning(f"[ProactiveOutreach] Load failed: {e}")

    def _save(self) -> None:
        try:
            with self._lock:
                self._path.parent.mkdir(parents=True, exist_ok=True)
                tmp = self._path.with_suffix(".tmp")
                with open(tmp, "w") as f:
                    json.dump(asdict(self._state), f, indent=2)
                import os; os.replace(tmp, self._path)
        except Exception as e:
            logger.warning(f"[ProactiveOutreach] Save failed: {e}")
