"""
cognition/relational_knowledge_graph.py
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RelationalKnowledgeGraph (v117) — typed, sourced facts about named
people the user mentions, separate from the flat fuzzy-searched
"personal_fact" episodic memory (ai_system.py).

The gap this closes
────────────────────
Before this: a fact like "Nino is my wife" or "Matthieu and Marion are
twins" had nowhere structured to live. The only extraction mechanism
in the whole codebase for relations (semantic_extractor.py's
_keyword_relations) is built for abstract topic concepts — generic
"related_to" links with no relation type, no confidence, no source,
no evidence — the wrong shape entirely for people, and unable to
represent something like "Matthieu is Marion's twin" as anything more
specific than "Matthieu is related_to Marion". That is exactly the
entity-resolution failure observed in practice: "Matthieu and Marion
the twins" became "Matthieu and his twin counterpart" (an unspecified
third person) because there was no structured place to record that
Marion herself IS the twin, not a placeholder for one.

Every edge here carries an epistemic_type:
    "fact"      — directly stated by the user, confidence 1.0
    "inference" — reserved for future use; NOT auto-generated by this
                  module. This module deliberately does not invent
                  inferences — that stays the LLM's job, kept honest by
                  prompt_fragment() below explicitly telling it which
                  facts exist and instructing it not to present
                  anything beyond them as remembered fact.

This module only ever stores what the user actually stated (extraction
is regex-based — approximate by construction, same honesty already
applied to ai_system.py's personal-fact extraction, not a claim of
complete named-entity resolution). It does not generate narrative
roles, symbolic interpretations, or self-concept claims — see
epistemic_integrity_engine.py + persona_bridge.py's Phase A3 for how
those are hedged instead.
"""

from __future__ import annotations

import json
import logging
import re
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from threading import RLock
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

DEFAULT_PATH = "data/persona/relational_graph.json"


@dataclass
class RelationEdge:
    entity_a:       str
    relation:       str     # e.g. "wife_of", "twin_of", "gender"
    entity_b:       str     # e.g. "the user", "Marion", "female"
    epistemic_type: str = "fact"      # "fact" | "inference" | "narrative"
    confidence:     float = 1.0
    source:         str = "user_stated"
    evidence:       str = ""          # short quote/snippet, best-effort
    timestamp:      float = field(default_factory=time.time)

    def as_sentence(self) -> str:
        """Plain-English rendering for prompt injection."""
        rel = self.relation.replace("_", " ")
        if self.relation == "gender":
            return f"{self.entity_a} is {self.entity_b}."
        if self.entity_b == "the user":
            return f"{self.entity_a} is the user's {rel.replace(' of', '')}."
        return f"{self.entity_a} is {self.entity_b}'s {rel.replace(' of', '')}."


class RelationalKnowledgeGraph:
    """
    Small, append-only store of typed facts about named third parties.
    Not a full graph database — a flat list of edges is plenty for the
    scale this is meant for (a person's stated family/friend network),
    and keeps persistence/inspection trivial (same JSON-file pattern as
    every other cognition/*.py module).
    """

    _REL_WORDS = (
        r"wife|husband|spouse|partner|girlfriend|boyfriend|fianc[ée]e?|"
        r"mother|mom|mum|father|dad|papa|sister|brother|son|daughter|"
        r"cousin|aunt|uncle|grandmother|grandma|grandfather|grandpa|"
        r"nephew|niece|best friend|friend|boss|manager|colleague|"
        r"roommate|doctor|therapist"
    )
    _FWD_RE = re.compile(
        r"\b([A-Za-z][\w'-]{1,30})\s+is\s+my\s+(" + _REL_WORDS + r")\b", re.IGNORECASE
    )
    _REV_RE = re.compile(
        r"\bmy\s+(" + _REL_WORDS + r")(?:'s name)?\s+is\s+([A-Za-z][\w'-]{1,30})\b",
        re.IGNORECASE,
    )
    _TWIN_RE = re.compile(
        r"\b([A-Za-z][\w'-]{1,30})\s+and\s+([A-Za-z][\w'-]{1,30})\s+(?:are\s+|the\s+)?twins?\b",
        re.IGNORECASE,
    )
    _GENDER_RE = re.compile(
        r"\b([A-Za-z][\w'-]{1,30})\s+(?:is|'s)\s+(male|female)\b", re.IGNORECASE
    )
    _STOPWORDS = {"i", "it", "this", "that", "he", "she", "they", "we", "you"}

    def __init__(self, path: str = DEFAULT_PATH):
        self._path = Path(path)
        self._lock = RLock()
        self._edges: List[RelationEdge] = []
        self._load()

    # ── Extraction ───────────────────────────────────────────────────────

    def extract_and_store(self, text: str) -> List[RelationEdge]:
        """
        Regex-based extraction of stated facts from a single message.
        Returns the edges newly added (empty if none found or all were
        already-known duplicates). Approximate by construction — see
        module docstring.
        """
        added: List[RelationEdge] = []
        try:
            for m in self._FWD_RE.finditer(text):
                added += self._maybe_add(m.group(1), f"{m.group(2).lower().replace(' ', '_')}_of",
                                          "the user", text)
            for m in self._REV_RE.finditer(text):
                added += self._maybe_add(m.group(2), f"{m.group(1).lower().replace(' ', '_')}_of",
                                          "the user", text)
            for m in self._TWIN_RE.finditer(text):
                a, b = m.group(1), m.group(2)
                if a.lower() not in self._STOPWORDS and b.lower() not in self._STOPWORDS \
                        and a[0].isupper() and b[0].isupper():
                    added += self._maybe_add(a, "twin_of", b, text)
                    added += self._maybe_add(b, "twin_of", a, text)
            for m in self._GENDER_RE.finditer(text):
                name, gender = m.group(1), m.group(2).lower()
                if name.lower() not in self._STOPWORDS and name[0].isupper():
                    added += self._maybe_add(name, "gender", gender, text)
        except Exception as e:
            logger.debug(f"[RelationalGraph] extraction error: {e}")
        if added:
            self._save()
        return added

    def _maybe_add(self, entity_a: str, relation: str, entity_b: str, evidence: str) -> List[RelationEdge]:
        if entity_a.lower() in self._STOPWORDS or not entity_a[0].isupper():
            return []
        with self._lock:
            for e in self._edges:
                if e.entity_a == entity_a and e.relation == relation and e.entity_b == entity_b:
                    return []  # already known
            edge = RelationEdge(
                entity_a=entity_a, relation=relation, entity_b=entity_b,
                epistemic_type="fact", confidence=1.0, source="user_stated",
                evidence=evidence[:120],
            )
            self._edges.append(edge)
            logger.info(f"[RelationalGraph] Stored fact: {edge.as_sentence()}")
            return [edge]

    # ── Query ────────────────────────────────────────────────────────────

    def facts_about(self, name: str) -> List[RelationEdge]:
        with self._lock:
            return [e for e in self._edges
                    if e.entity_a.lower() == name.lower() or e.entity_b.lower() == name.lower()]

    def known_names(self) -> List[str]:
        with self._lock:
            names = set()
            for e in self._edges:
                names.add(e.entity_a)
                if e.entity_b != "the user":
                    names.add(e.entity_b)
            return sorted(names)

    def prompt_fragment(self, mentioned_names: Optional[List[str]] = None) -> str:
        """
        Grounded-facts block for injection into the chat system prompt.
        If mentioned_names is given, scopes to facts about those people
        (keeps the block short); otherwise includes everything known.
        Always ends with the instruction that is the actual point of
        this module: don't invent roles/meaning beyond what's listed.
        """
        with self._lock:
            if mentioned_names:
                wanted = {n.lower() for n in mentioned_names}
                edges = [e for e in self._edges
                         if e.entity_a.lower() in wanted or e.entity_b.lower() in wanted]
            else:
                edges = list(self._edges)
        if not edges:
            return ""
        lines = [e.as_sentence() for e in edges]
        return (
            "[Grounded relational facts — these are the ONLY facts you actually "
            "know about these people]\n" + "\n".join(lines) +
            "\nDo not invent roles, personalities, symbolic meaning, or "
            "relationships beyond what's listed above. If asked about someone "
            "not covered here, or about an aspect not covered above, say "
            "plainly that you don't have that on record rather than "
            "constructing an interpretation and presenting it as memory."
        )

    # ── Persistence ──────────────────────────────────────────────────────

    def _load(self) -> None:
        try:
            if self._path.exists():
                data = json.loads(self._path.read_text(encoding="utf-8"))
                self._edges = [RelationEdge(**d) for d in data.get("edges", [])]
        except Exception as e:
            logger.warning(f"[RelationalGraph] load failed (starting empty): {e}")

    def _save(self) -> None:
        try:
            self._path.parent.mkdir(parents=True, exist_ok=True)
            with self._lock:
                data = {"edges": [asdict(e) for e in self._edges]}
            self._path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        except Exception as e:
            logger.warning(f"[RelationalGraph] save failed: {e}")
