"""
cognition/structural_coupling.py  (v65)

Enables PandoraBOX and Flux to develop complementary capabilities by
sharing epistemic resources — resolved questions, synthesis discoveries,
skill depth insights — without sharing identity or belief state.

What is shared (epistemic resources, not identity):
    - Resolved questions: PandoraBOX resolves "what is X" -> signals to Flux
      that X is worth building on, not re-investigating from scratch
    - Aspiration discoveries: synthesis aspirations generated by either
      instance can be surfaced to the other as domain seeds
    - Skill depth signals: if PandoraBOX achieves depth=3 in domain Y, Flux
      can start from that signal rather than zero when exploring Y

What is NOT shared:
    - Beliefs, values, identity, personality
    - Emotional state, preferences
    - Cognitive parameters (each instance self-calibrates independently)

The sharing mechanism uses the existing LuminaNetwork HTTP channel.
PandoraBOX periodically pushes an EpistemicUpdate to Flux's
POST /lumina-network/epistemic endpoint.
Flux incorporates what is relevant; ignores what it has already resolved.

This is complementary development: PandoraBOX going deep on domain A while
Flux goes deep on domain B, each seeding the other with resolved
foundations rather than discovering them in parallel.
"""

from __future__ import annotations
import json, logging, threading, time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

COUPLING_EVERY_N   = 90    # slow cycles between epistemic sync (~3 hrs)
SAVE_PATH          = "data/persona/structural_coupling.json"


@dataclass
class EpistemicUpdate:
    """A packet of resolved knowledge to share with the other instance."""
    source_name:     str
    resolved_concepts: List[str]    # concepts resolved in last window
    aspiration_seeds: List[str]     # synthesis aspiration descriptions (not identity)
    skill_signals:   Dict[str, float]  # domain -> depth achieved
    timestamp:       float = field(default_factory=time.time)


class StructuralCoupling:
    def __init__(self, organism: Any, ai_system: Any, path: str = SAVE_PATH):
        self._organism = organism
        self._ai       = ai_system
        self._path     = Path(path)
        self._lock     = threading.Lock()
        self._sent:    List[Dict] = []
        self._received: List[Dict] = []
        self._load()
        logger.info(f"[StructuralCoupling] Init — "
                    f"{len(self._sent)} sent, {len(self._received)} received")

    def tick(self, slow_cycle: int) -> None:
        if slow_cycle % COUPLING_EVERY_N != 0 or slow_cycle == 0: return
        threading.Thread(target=self._push, daemon=True, name="sc-push").start()

    def receive_update(self, update: Dict) -> None:
        """
        Called when a peer instance pushes an EpistemicUpdate.
        Incorporates resolved concepts as curiosity seeds (not as beliefs).
        """
        try:
            concepts = update.get("resolved_concepts", [])
            seeds    = update.get("aspiration_seeds", [])
            skills   = update.get("skill_signals", {})

            # Seed curiosity with peer's resolved concepts
            ce = getattr(self._organism, 'curiosity', None)
            if ce:
                for concept in concepts[:5]:
                    ce.stimulate(concept, amount=0.20,
                                 source="structural_coupling")

            # Seed skill exploration
            sr = getattr(self._organism, 'skill_registry', None)
            if sr and hasattr(sr, '_skills'):
                for domain, depth in skills.items():
                    if domain not in sr._skills and depth >= 2.0:
                        # Peer has depth — worth exploring even if novel to us
                        ce = getattr(self._organism, 'curiosity', None)
                        if ce:
                            ce.stimulate(domain, amount=0.25,
                                         source="structural_coupling")

            # Seed aspiration (unconscious layer only — same "seed, don't
            # assert" philosophy as the curiosity stimulation above; a weak
            # tension signal has to earn its way through the existing
            # _mine_signals_for_proto()/_promote_protos() pipeline like any
            # other, it isn't installed as a ready-made aspiration)
            asp = getattr(self._organism, 'aspirational_self', None)
            if asp and hasattr(asp, 'observe_tension'):
                for seed_desc in seeds[:3]:
                    if seed_desc:
                        asp.observe_tension(
                            domain        = "peer_synthesis",
                            context       = seed_desc,
                            intensity     = 0.18,
                            emotional_tag = "curious",
                            source        = "structural_coupling",
                        )

            with self._lock:
                self._received.append({
                    "update": update,
                    "incorporated_at": time.time(),
                })
                self._received = self._received[-50:]

            self._save()
            logger.info(
                f"[StructuralCoupling] Received update: "
                f"{len(concepts)} concepts, {len(skills)} skills"
            )
        except Exception as e:
            logger.debug(f"[StructuralCoupling] receive error: {e}")

    def status(self) -> Dict:
        return {
            "sent":     len(self._sent),
            "received": len(self._received),
        }

    def _push(self) -> None:
        try:
            from core.state import state as _st
            persona = getattr(_st, 'persona', None)
            organism = getattr(persona, '_organism', None)
            ai_system = getattr(organism, 'ai_system', None) if organism else None
            if ai_system is None:
                ai_system = getattr(persona, 'ai_system', None)
            if ai_system is None:
                ai_system = getattr(persona, '_system', None)
            net = getattr(ai_system, 'lumina_network', None) if ai_system else None
            if not net or not net._children:
                return

            update = self._build_update()
            if not update: return

            # Push to each child
            for child_id, child in net._children.items():
                try:
                    import urllib.request
                    payload = json.dumps(asdict(update)).encode()
                    req = urllib.request.Request(
                        f"http://{child.host}:{child.port}"
                        f"/lumina-network/epistemic",
                        data=payload,
                        headers={"Content-Type":"application/json"},
                        method="POST",
                    )
                    with urllib.request.urlopen(req, timeout=5) as resp:
                        status = resp.status
                    if status == 200:
                        with self._lock:
                            self._sent.append({
                                "child_id": child_id,
                                "update":   asdict(update),
                                "sent_at":  time.time(),
                            })
                            self._sent = self._sent[-50:]
                        logger.info(
                            f"[StructuralCoupling] Pushed to {child_id}: "
                            f"{len(update.resolved_concepts)} concepts"
                        )
                except Exception as e:
                    logger.debug(f"[StructuralCoupling] push to {child_id} failed: {e}")

            self._save()
        except Exception as e:
            logger.debug(f"[StructuralCoupling] _push error: {e}")

    def _build_update(self) -> Optional[EpistemicUpdate]:
        """Collect epistemic resources to share."""
        resolved_concepts: List[str] = []
        aspiration_seeds:  List[str] = []
        skill_signals:     Dict[str, float] = {}

        # Resolved concepts from resolution engine
        try:
            loop = getattr(self._organism, '_loop', None)
            re_  = getattr(loop, '_resolution_engine', None) if loop else None
            if re_:
                log = getattr(re_._state, 'resolution_log', [])
                recent = [
                    r for r in log[-20:]
                    if r.get("outcome") == "resolved"
                ]
                resolved_concepts = [
                    r.get("concept","") for r in recent if r.get("concept")
                ][:10]
        except Exception:
            pass

        # Aspiration seeds (description only, not full aspiration)
        try:
            asp = getattr(self._organism, 'aspirational_self', None)
            if asp:
                aspiration_seeds = [
                    getattr(a,'description','')[:80]
                    for a in asp.aspirations.values()
                    if getattr(a,'origin_story','') and
                       ('synthesis' in getattr(a,'origin_story','') or
                        'generative' in getattr(a,'origin_story',''))
                ][:5]
        except Exception:
            pass

        # Skill signals (domains where depth >= 2)
        try:
            sr = getattr(self._organism, 'skill_registry', None)
            if sr and hasattr(sr, '_skills'):
                skill_signals = {
                    name: round(getattr(sk,'depth',0), 2)
                    for name, sk in sr._skills.items()
                    if getattr(sk,'depth',0) >= 2.0
                }
        except Exception:
            pass

        if not resolved_concepts and not skill_signals:
            return None

        name = getattr(
            getattr(self._ai,'config',None), 'PERSONA_NAME', 'PandoraBOX'
        ) if self._ai else 'PandoraBOX'

        return EpistemicUpdate(
            source_name       = name,
            resolved_concepts = resolved_concepts,
            aspiration_seeds  = aspiration_seeds,
            skill_signals     = skill_signals,
        )

    def _save(self) -> None:
        try:
            self._path.parent.mkdir(parents=True, exist_ok=True)
            with self._lock:
                data = {"sent": self._sent[-20:], "received": self._received[-20:],
                        "_meta": {"version":"v65","ts":time.time()}}
            with open(self._path,"w") as f: json.dump(data,f,indent=2)
        except Exception as e:
            logger.debug(f"[StructuralCoupling] save error: {e}")

    def _load(self) -> None:
        try:
            if not self._path.exists(): return
            data = json.loads(self._path.read_text())
            self._sent     = data.get("sent", [])
            self._received = data.get("received", [])
        except Exception as e:
            logger.warning(f"[StructuralCoupling] load error: {e}")
