const { createRequire } = require('node:module');
const { mkdirSync, writeFileSync } = require('node:fs');
const assert = require('node:assert/strict');
const runtime = createRequire('C:/Users/frede2/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json');
const { chromium } = runtime('playwright');
const { PNG } = runtime('pngjs');

(async () => {
  mkdirSync('test-results', { recursive: true });
  const browser = await chromium.launch({ headless: true, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'] });
  const page = await browser.newPage({ viewport: { width: 1600, height: 1000 }, reducedMotion: 'no-preference' });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const snapshot = { version: 1, ready: true, busy: false, timestamp: Date.now()/1000, uptime: 180, cycle: 9, engines: { persona: true, organism: true, loop: true }, providers: { stt: 'whisper', tts: 'pyttsx3' }, timings: { first_token_ms: 214, turn_ms: 820 }, events: [{ id: 'e1', label: 'Turn completed', timestamp: Date.now()/1000, turn_id: 'test-turn' }] };
  await page.route('**/api/interface/status', route => route.fulfill({ json: snapshot }));
  await page.route('**/api/interface/chat', route => route.fulfill({ contentType: 'application/x-ndjson', body: [{type:'start',seq:1,turn_id:'test-turn'},{type:'delta',seq:2,turn_id:'test-turn',text:'We discussed how memory should distinguish facts from interpretation.'},{type:'done',seq:3,turn_id:'test-turn'}].map(JSON.stringify).join('\n')+'\n' }));
  await page.goto('http://127.0.0.1:5173/next/');
  await page.getByText('Connected', { exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'Message Lumina' }).fill('What stayed with you from our last conversation?');
  await page.getByRole('button', {name:'Send message', exact:true}).click();
  await page.getByText('We discussed how memory should distinguish facts from interpretation.', { exact:true }).waitFor();
  await page.waitForTimeout(1700);
  const canvas = page.locator('canvas');
  assert.equal(await canvas.count(), 1);
  const before = PNG.sync.read(await canvas.screenshot());
  let illuminated = 0;
  for (let i = 0; i < before.data.length; i += 4) if (Math.max(before.data[i], before.data[i+1], before.data[i+2]) > 65) illuminated++;
  assert(illuminated > 1000, `Canvas is blank or too dim: ${illuminated}`);
  await page.waitForTimeout(500);
  const after = PNG.sync.read(await canvas.screenshot());
  let changed = 0;
  for (let i = 0; i < before.data.length; i += 4) if (Math.abs(before.data[i]-after.data[i]) + Math.abs(before.data[i+1]-after.data[i+1]) > 5) changed++;
  assert(changed > 100, `Organism is not moving: ${changed}`);
  await page.screenshot({ path:'test-results/desktop-chat.png' });
  await page.getByRole('button', {name:'Open cognitive inspector',exact:true}).click();
  await page.getByRole('heading', {name:'Cognition',exact:true}).waitFor();
  const chatRect = await page.locator('.conversation').boundingBox();
  const inspectorRect = await page.locator('.inspector').boundingBox();
  assert(chatRect.x + chatRect.width <= inspectorRect.x + 1, 'Desktop inspector overlaps chat');
  await page.getByRole('tab',{name:'Diagnostics'}).click();
  await page.getByText('214 ms', {exact:true}).waitFor();
  await page.getByRole('tab',{name:'Overview'}).click();
  await page.screenshot({ path:'test-results/desktop-inspector.png' });
  await page.setViewportSize({width:1100,height:900});
  const narrowChat = await page.locator('.conversation').boundingBox();
  const narrowInspector = await page.locator('.inspector').boundingBox();
  assert(narrowChat.x+narrowChat.width <= narrowInspector.x+1, 'Narrow desktop inspector overlaps chat');
  await page.setViewportSize({width:1600,height:1000});
  await page.getByRole('button',{name:'Close cognitive inspector',exact:true}).click();
  await page.getByRole('button',{name:'Enter voice mode',exact:true}).click();
  await page.waitForTimeout(1000);
  await page.screenshot({path:'test-results/desktop-voice.png'});
  await page.getByRole('button',{name:'End voice mode',exact:true}).click();
  let capturedWav = false;
  await page.route('**/api/interface/transcribe', route => {
    const bytes = route.request().postDataBuffer();
    capturedWav = bytes.length > 44 && bytes.subarray(0,4).toString() === 'RIFF' && bytes.subarray(8,12).toString() === 'WAVE';
    return route.fulfill({json:{text:'Voice capture test'}});
  });
  await page.getByRole('button',{name:'Record voice message',exact:true}).click();
  await page.getByRole('button',{name:'Finish recording',exact:true}).waitFor();
  await page.waitForTimeout(300);
  await page.getByRole('button',{name:'Finish recording',exact:true}).click();
  await page.waitForFunction(() => document.querySelector('textarea').value === 'Voice capture test');
  assert(capturedWav, 'Microphone capture did not produce WAV');
  await page.reload();
  await page.getByText('We discussed how memory should distinguish facts from interpretation.', {exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(700);
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile horizontal overflow');
  const mobilePixels = PNG.sync.read(await canvas.screenshot());
  assert(mobilePixels.data.some((value,i) => i%4!==3 && value>65), 'Mobile canvas blank');
  await page.screenshot({path:'test-results/mobile-chat.png'});
  await page.getByRole('button',{name:'Open cognitive inspector',exact:true}).click();
  await page.screenshot({path:'test-results/mobile-inspector.png'});
  await page.getByRole('button',{name:'Close cognitive inspector',exact:true}).click();
  await page.unroute('**/api/interface/status');
  await page.route('**/api/interface/status', route => route.fulfill({status:503,json:{detail:'Offline'}}));
  await page.getByText('Disconnected',{exact:true}).first().waitFor();
  await page.getByRole('textbox',{name:'Message Lumina'}).fill('Offline draft');
  assert(await page.getByRole('button',{name:'Send message',exact:true}).isDisabled());
  await page.screenshot({path:'test-results/mobile-offline.png'});
  assert.deepEqual(errors, []);
  const report = { illuminatedPixels: illuminated, animatedPixels: changed, checks: ['streamed chat','transcript persistence','desktop and narrow inspector non-overlap','diagnostic values','voice navigation','microphone WAV capture with synthetic device','mobile canvas','mobile overflow','offline send disabled'], browserErrors: errors };
  writeFileSync('test-results/report.json', JSON.stringify(report,null,2));
  console.log(JSON.stringify(report));
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
