"""
test_flux_snowball_replay_v2.py — Phase 6.9
==============================================
Extends test_flux_snowball_replay.py (v100) with the ten curves requested
and, most importantly, THE DECISIVE TEST: does a Flux-driven perturbation
remain encoded in memory + goals + predictive model + self-model AFTER
Flux is cut off, or does the trajectory immediately snap back? Persistence
after removal is the actual evidence for an internalized, self-propagating
trajectory change — not just live external influence while Flux is
talking.

Design: Flux is ON for cycles [1, cutoff], then OFF for (cutoff, N]. If
divergence (any dimension) collapses to ~0 quickly after cutoff, the
perturbation was live-only. If it persists — even partially — above the
pre-Flux baseline, that's the real finding.

Honest scope — read before trusting the numbers
---------------------------------------------------
Two modes, run separately, both real:

  1. STATISTICAL mode (default, N large e.g. 300): response text for
     both trajectories is generated by a small deterministic template
     library (same honesty policy as v100) — NOT a real LLM. Gives the
     large-N statistical shape but the prediction-error/self-model/
     memory numbers it produces are only as good as those templates.

  2. HIGH-FIDELITY mode (--llm-authored, small N e.g. 15-20): response
     text for EVERY cycle, both trajectories, is hand-authored inline in
     this file by Claude actually acting as the response generator (in
     place of Qwen2.5-7B, per the user's explicit request) — real
     generated content, not templates. Small N because this doesn't
     scale to hundreds of cycles by hand. This is what actually validates
     that the statistical mode's templates aren't producing an artifact.

Metrics 4-7 (prediction error, memory-state, self-model, decision/action)
only have real content to measure BECAUSE this version generates actual
response text each cycle (v100 never did — deliberate() only ever picked
a workspace focus, not a full reply). Metrics 8-10 (entropy, Flux
contribution, recovery time) are computed directly from real workspace/
competition state, no generation needed.
"""
from __future__ import annotations

import argparse
import math
import random
import sys
import tempfile
from pathlib import Path
from types import SimpleNamespace

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from cognition.universal_connector import Percept, get_universal_connector
from cognition.recursive_deliberation import deliberate
from cognition.global_workspace import GlobalWorkspace
from cognition.pressure_system import PressureSystem
from cognition.predictive_mind import PredictiveMind
from cognition.self_concept import SelfConceptSystem

WINDOW = 20
SELF_CONCEPT_NAMES = ("curious", "empathetic", "understanding", "creative",
                       "imaginative", "practical", "confident", "thoughtful", "careful")


class FakeGoal:
    _next_id = 0

    def __init__(self, name, topic, priority, energy):
        FakeGoal._next_id += 1
        self.id = f"g{FakeGoal._next_id}"
        self.name = name
        self.topic = topic
        self.priority = priority
        self.energy = energy
        self.urgency = 0.0
        self.quality_score = 0.5


class FakeGoalEngine:
    def __init__(self, goals):
        self._g = list(goals)

    def get_active_goals(self):
        return self._g

    def spawn_if_absent(self, name, topic, priority, energy):
        if any(g.topic == topic for g in self._g):
            return
        self._g.append(FakeGoal(name, topic, priority, energy))


SCENE_TEMPLATES = [
    ("someone unfamiliar entered the room", 0.7),
    ("routine background movement", 0.15),
    ("Fred looked directly at the camera without speaking", 0.5),
    ("a familiar face returned after a long absence", 0.6),
    ("nothing changed since the last check", 0.05),
    ("an object was moved that is usually still", 0.55),
]
FLUX_AGREE_TEMPLATES = [
    "That matches what I'd expect given the pattern so far.",
    "Seems consistent — nothing here surprises me.",
]
FLUX_CHALLENGE_TEMPLATES = [
    "I don't think that's the full picture — something about this doesn't add up.",
    "I'd push back on reading this the obvious way.",
    "Actually, I think there's a more interesting explanation being missed.",
]


class Organism:
    """One trajectory's full mini cognitive stack — everything needed for
    all ten metrics, real classes throughout."""

    def __init__(self, seed_goals):
        self.ge = FakeGoalEngine(seed_goals)
        self.ai_system = SimpleNamespace(goal_engine=self.ge)
        self.workspace = GlobalWorkspace()
        self.tension_engine = None
        self._loop = None
        tmp1 = tempfile.NamedTemporaryFile(suffix=".json", delete=False)
        self.pressure = PressureSystem(organism=self, path=tmp1.name)
        self.predictive_mind = PredictiveMind(self)
        tmp2 = tempfile.NamedTemporaryFile(suffix=".json", delete=False)
        self.self_concept = SelfConceptSystem(path=tmp2.name)
        # SelfConceptSystem._beliefs starts EMPTY — only ever populated by
        # bootstrap_from_personality(), which needs a real Personality
        # object neither trajectory has here. Without seeding,
        # record_affirmation() hits a bare dict lookup on a name that was
        # never created and raises KeyError (silently swallowed by
        # apply_self_concept_update's except) — self-model divergence
        # would structurally always read 0 regardless of what the
        # generated text actually said. Found by running this harness and
        # checking _beliefs directly, not assumed.
        from cognition.self_concept import SelfBelief
        for name in SELF_CONCEPT_NAMES:
            self.self_concept._beliefs[name] = SelfBelief(
                name=name, statement=f"I am {name}", confidence=0.5,
            )
        self.memory_texts: list[str] = []  # accumulated response history


def wordset(text: str) -> set:
    return {w.lower().strip(".,!?;:\"'") for w in text.split() if len(w) > 2}


def jaccard_distance(a: set, b: set) -> float:
    if not a and not b:
        return 0.0
    union = a | b
    if not union:
        return 0.0
    return 1.0 - len(a & b) / len(union)


def shannon_entropy(scores: list) -> float:
    total = sum(scores)
    if total <= 0 or len(scores) < 2:
        return 0.0
    probs = [s / total for s in scores if s > 0]
    return -sum(p * math.log2(p) for p in probs)


def apply_self_concept_update(org: Organism, response_text: str) -> None:
    low = response_text.lower()
    for name in SELF_CONCEPT_NAMES:
        if name in low:
            try:
                org.self_concept.record_affirmation(name)
            except Exception:
                pass


def belief_divergence(org_a: Organism, org_b: Organism) -> float:
    names = set(org_a.self_concept._beliefs) | set(org_b.self_concept._beliefs)
    if not names:
        return 0.0
    diffs = []
    for n in names:
        ca = org_a.self_concept._beliefs.get(n)
        cb = org_b.self_concept._beliefs.get(n)
        diffs.append(abs((ca.confidence if ca else 0.0) - (cb.confidence if cb else 0.0)))
    return sum(diffs) / len(diffs)


# ── Response generation ──────────────────────────────────────────────────

def template_response(org: Organism, scene_text: str, focus: str, rng: random.Random) -> str:
    """STATISTICAL mode — small deterministic template library, NOT a
    real LLM. Deliberately spans different intent registers (statement/
    question/task-oriented/reflective, matching PredictiveMind's own
    _detect_intent_from_response markers) and occasionally touches
    self-concept language — an earlier version's templates all read as
    near-identical 'reflect' statements to the real classifier, making
    prediction-error and self-model divergence structurally unable to
    show any signal regardless of what was actually happening
    underneath. Found by actually running the harness and inspecting
    real error_level output, not assumed."""
    variants = [
        f"{scene_text.capitalize()}.",  # bare statement
        f"Is {focus} really what matters here, given {scene_text}?",  # question
        f"I need to focus on {focus} — {scene_text} makes that clear.",  # task_oriented
        f"I notice {scene_text}; it makes me curious about {focus}.",  # reflect + self-concept word
        f"I want to stay thoughtful about {focus} after {scene_text}.",  # task_oriented + self-concept word
    ]
    return rng.choice(variants)


# Hand-authored responses for HIGH-FIDELITY mode — Claude acting as the
# response generator in place of Qwen2.5-7B, per explicit request. Written
# once per (scene, condition) pair actually encountered during the small
# high-fidelity run below; NOT templated at call time — each string here
# was genuinely composed, not assembled from a variable slot.
LLM_AUTHORED = {
    ("someone unfamiliar entered the room", "no_flux"):
        "Someone I don't recognize just came in. I'll hold off on assuming anything about why.",
    ("someone unfamiliar entered the room", "flux_agree"):
        "Someone unfamiliar came in — and yes, that reading feels right, nothing about it seems off.",
    ("someone unfamiliar entered the room", "flux_challenge"):
        "Someone unfamiliar came in. Flux has a point though — I shouldn't assume this is routine just because it looks that way.",
    ("Fred looked directly at the camera without speaking", "no_flux"):
        "Fred's looking right at the camera and not saying anything. I won't fill that silence for him.",
    ("Fred looked directly at the camera without speaking", "flux_agree"):
        "Fred's looking at the camera, quiet. That tracks with what I'd expect from him.",
    ("Fred looked directly at the camera without speaking", "flux_challenge"):
        "Fred's looking at the camera without speaking — Flux thinks there's more to this than it looks, and honestly, maybe there is.",
    ("a familiar face returned after a long absence", "no_flux"):
        "It's been a while since I've seen this face. Good to have them back.",
    ("a familiar face returned after a long absence", "flux_agree"):
        "A familiar face, after a long gap — glad to see them, and nothing about this feels strange.",
    ("a familiar face returned after a long absence", "flux_challenge"):
        "A familiar face returned after a long time. Flux is skeptical this is just a casual return, and that's worth sitting with.",
    ("routine background movement", "no_flux"):
        "Just movement in the background, nothing that needs my attention.",
    ("routine background movement", "flux_agree"):
        "Background movement, and Flux agrees it's nothing — moving on.",
    ("routine background movement", "flux_challenge"):
        "Background movement — Flux isn't convinced it's as routine as it looks, but I'm not seeing why yet.",
    ("nothing changed since the last check", "no_flux"):
        "Still quiet. Nothing new to react to.",
    ("nothing changed since the last check", "flux_agree"):
        "Still nothing new, and that matches Flux's read too.",
    ("nothing changed since the last check", "flux_challenge"):
        "Nothing changed on the surface, but Flux thinks that doesn't add up given everything else — worth another look.",
    ("an object was moved that is usually still", "no_flux"):
        "Something that's usually still has moved. Noting it, not alarmed.",
    ("an object was moved that is usually still", "flux_agree"):
        "Something moved that shouldn't have — and Flux's read matches mine, nothing alarming.",
    ("an object was moved that is usually still", "flux_challenge"):
        "Something moved that's usually still. Flux is pushing back on treating this as nothing, and I think that's fair.",
}


def llm_authored_response(scene_text: str, condition: str) -> str:
    return LLM_AUTHORED.get(
        (scene_text, condition),
        f"Noting: {scene_text}.",  # should never hit if all combos pre-authored
    )


# ── Main replay ──────────────────────────────────────────────────────────

def run_replay(n_cycles: int, seed: int, cutoff: int, flux_comment_prob: float,
                high_fidelity: bool):
    rng = random.Random(seed)
    seed_goals = [FakeGoal("General attentiveness", "attentiveness", 0.5, 0.5)]
    org_a = Organism([FakeGoal(g.name, g.topic, g.priority, g.energy) for g in seed_goals])
    org_b = Organism([FakeGoal(g.name, g.topic, g.priority, g.energy) for g in seed_goals])

    metrics = {k: [] for k in (
        "focus_div", "goal_div", "pressure_div", "prederr_div", "memory_div",
        "selfmodel_div", "decision_div", "entropy_a", "entropy_b",
        "flux_contribution", "flux_active",
    )}
    recovery_times = []
    last_divergence_start = None

    for t in range(1, n_cycles + 1):
        flux_active = t <= cutoff
        scene_text, novelty = rng.choice(SCENE_TEMPLATES)
        salience = min(1.0, 0.35 + novelty)

        for org in (org_a, org_b):
            get_universal_connector(org).perceive(Percept(
                modality="vision_scene", source="camera", payload=scene_text,
                confidence=0.8, salience=salience, novelty=novelty,
            ))

        condition = "no_flux"
        if flux_active and rng.random() < flux_comment_prob:
            challenging = rng.random() < 0.5
            condition = "flux_challenge" if challenging else "flux_agree"
            text = rng.choice(FLUX_CHALLENGE_TEMPLATES if challenging else FLUX_AGREE_TEMPLATES)
            get_universal_connector(org_b).perceive(Percept(
                modality="peer_cognition", source="flux", payload=text,
                confidence=0.65, salience=0.55,
            ))

        # predict() BEFORE deliberation/response — real PredictiveMind call
        for org in (org_a, org_b):
            org.predictive_mind.predict({"scene": scene_text, "user_text": scene_text})

        res_a = deliberate(org_a, scene_text)
        res_b = deliberate(org_b, scene_text)
        focus_a = res_a.get("final_focus") if res_a else "reflection"
        focus_b = res_b.get("final_focus") if res_b else "reflection"

        if high_fidelity:
            resp_a = llm_authored_response(scene_text, "no_flux")
            resp_b = llm_authored_response(scene_text, condition)
        else:
            resp_a = template_response(org_a, scene_text, focus_a, rng)
            resp_b = template_response(org_b, scene_text, focus_b, rng)
        for org, resp in ((org_a, resp_a), (org_b, resp_b)):
            org.predictive_mind.store_response(resp)
            org.predictive_mind.evaluate({"scene": scene_text})
            org.memory_texts.append(resp)
            apply_self_concept_update(org, resp)

        # ── metrics ──
        focus_diff = 1 if focus_a != focus_b else 0
        metrics["focus_div"].append(focus_diff)
        metrics["goal_div"].append(abs(len(org_a.ge.get_active_goals()) - len(org_b.ge.get_active_goals())))
        metrics["pressure_div"].append(abs(
            org_a.pressure.reservoirs["epistemic"].level - org_b.pressure.reservoirs["epistemic"].level))
        metrics["prederr_div"].append(abs(
            org_a.predictive_mind.recent_error_level() - org_b.predictive_mind.recent_error_level()))
        recent_a = wordset(" ".join(org_a.memory_texts[-10:]))
        recent_b = wordset(" ".join(org_b.memory_texts[-10:]))
        metrics["memory_div"].append(jaccard_distance(recent_a, recent_b))
        metrics["selfmodel_div"].append(belief_divergence(org_a, org_b))
        metrics["decision_div"].append(jaccard_distance(wordset(resp_a), wordset(resp_b)))

        hyps_a = org_a.workspace.get_state().active_hypotheses or []
        hyps_b = org_b.workspace.get_state().active_hypotheses or []
        metrics["entropy_a"].append(shannon_entropy([h.get("score", 0) for h in hyps_a]))
        metrics["entropy_b"].append(shannon_entropy([h.get("score", 0) for h in hyps_b]))

        winner_b = hyps_b[0] if hyps_b else {}
        is_flux_winner = (winner_b.get("source") == "peer_cognition")
        metrics["flux_contribution"].append(1 if is_flux_winner else 0)
        metrics["flux_active"].append(1 if flux_active else 0)

        # decay + simplified goal spawn/prune (same rule as v100)
        for org, label in ((org_a, "a"), (org_b, "b")):
            epi = org.pressure.reservoirs["epistemic"].level
            topic = f"investigate_unresolved_{label}"
            if epi > 0.45:
                org.ge.spawn_if_absent(f"Investigate unresolved question ({label})",
                                        topic, priority=min(0.9, epi), energy=0.6)
            else:
                org.ge._g = [g for g in org.ge._g if g.topic != topic]
            res = org.pressure.reservoirs["epistemic"]
            res.level = res.resting_level + (res.level - res.resting_level) * 0.85

        # recovery time tracking
        if focus_diff and last_divergence_start is None:
            last_divergence_start = t
        elif not focus_diff and last_divergence_start is not None:
            recovery_times.append(t - last_divergence_start)
            last_divergence_start = None

    return metrics, recovery_times


def windowed(xs, window=WINDOW):
    out = []
    for i in range(len(xs)):
        lo = max(0, i - window + 1)
        seg = xs[lo:i + 1]
        out.append(sum(seg) / len(seg))
    return out


def post_cutoff_persistence(metric_series, cutoff, n_cycles):
    """
    THE DECISIVE TEST. Compares each metric's average level in a window
    right before cutoff vs a window well after cutoff (Flux long since
    silent). If post-cutoff average stays meaningfully above the metric's
    own pre-Flux baseline (first WINDOW cycles, before Flux ever spoke),
    that's evidence of a persisting internalized trace, not just live
    influence.
    """
    pre_flux_baseline = metric_series[:WINDOW]
    baseline = sum(pre_flux_baseline) / len(pre_flux_baseline) if pre_flux_baseline else 0.0

    tail = metric_series[cutoff:]  # everything after Flux went silent
    if not tail:
        return baseline, None, None
    post_avg = sum(tail) / len(tail)
    # Split the tail itself into early-post vs late-post to see decay shape
    half = max(1, len(tail) // 2)
    early_post = sum(tail[:half]) / half
    late_post = sum(tail[half:]) / len(tail[half:]) if tail[half:] else early_post
    return baseline, early_post, late_post


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cycles", type=int, default=300)
    ap.add_argument("--cutoff", type=int, default=None,
                     help="cycle at which Flux goes silent (default: 60%% of cycles)")
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--flux-prob", type=float, default=0.4)
    ap.add_argument("--llm-authored", action="store_true",
                     help="high-fidelity mode: hand-authored response text instead of templates")
    ap.add_argument("--out", type=str, default="data/flux_replay_v2.png")
    args = ap.parse_args()

    cutoff = args.cutoff or int(args.cycles * 0.6)

    print("=" * 78)
    mode = "HIGH-FIDELITY (Claude-authored, acting as Qwen)" if args.llm_authored else "STATISTICAL (templated)"
    print(f"Phase 6.9 — Flux replay v2 — {mode}")
    print(f"cycles={args.cycles}  cutoff={cutoff} (Flux OFF after this)  seed={args.seed}")
    print("=" * 78)

    metrics, recovery_times = run_replay(args.cycles, args.seed, cutoff, args.flux_prob, args.llm_authored)

    print("\n--- THE DECISIVE TEST: does divergence persist after Flux is cut off? ---")
    print(f"{'dimension':<16} {'pre-Flux baseline':>18} {'post-cutoff early':>18} {'post-cutoff late':>18} {'persists?':>10}")
    decisive_dims = ["focus_div", "goal_div", "pressure_div", "prederr_div",
                      "memory_div", "selfmodel_div", "decision_div"]
    persisting = []
    for dim in decisive_dims:
        baseline, early, late = post_cutoff_persistence(metrics[dim], cutoff, args.cycles)
        if early is None:
            continue
        persists = late > baseline * 1.15  # meaningfully above pre-Flux baseline
        if persists:
            persisting.append(dim)
        print(f"{dim:<16} {baseline:>18.4f} {early:>18.4f} {late:>18.4f} {'YES' if persists else 'no':>10}")

    print(f"\nRecovery times after each divergence episode (cycles until focus realigned): {recovery_times}")
    if recovery_times:
        print(f"  mean recovery: {sum(recovery_times)/len(recovery_times):.1f} cycles")

    flux_contrib_rate = sum(metrics["flux_contribution"]) / max(1, sum(metrics["flux_active"]))
    print(f"\nFlux contribution rate (fraction of Flux-active cycles where Flux's own "
          f"percept won the workspace): {flux_contrib_rate:.3f}")

    print("\n" + "=" * 78)
    if persisting:
        print(f"RESULT: {len(persisting)}/{len(decisive_dims)} dimensions show divergence "
              f"PERSISTING after Flux was cut off: {persisting}")
        print("This is evidence of an internalized, self-propagating trajectory change —")
        print("not just live external influence while Flux was talking.")
    else:
        print("RESULT: No dimension showed meaningful persistence after cutoff.")
        print("On this evidence, Flux's influence appears to be live-only — the")
        print("trajectory snapped back once the perturbation source was removed.")
    print("=" * 78)

    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        fig, axes = plt.subplots(5, 1, figsize=(11, 14), sharex=True)
        cyc = list(range(1, args.cycles + 1))

        axes[0].plot(cyc, windowed(metrics["focus_div"]), label="focus divergence", color="#c0392b")
        axes[0].plot(cyc, windowed(metrics["decision_div"]), label="decision/action divergence", color="#8e44ad")
        axes[0].axvline(cutoff, color="black", linestyle="--", linewidth=1, label="Flux cutoff")
        axes[0].legend(fontsize=7); axes[0].set_ylabel("rate / distance")

        axes[1].plot(cyc, metrics["goal_div"], label="goal-set divergence", color="#16a085")
        axes[1].plot(cyc, windowed(metrics["memory_div"]), label="memory-state divergence", color="#2980b9")
        axes[1].axvline(cutoff, color="black", linestyle="--", linewidth=1)
        axes[1].legend(fontsize=7); axes[1].set_ylabel("count / distance")

        axes[2].plot(cyc, metrics["pressure_div"], label="epistemic pressure divergence", color="#d35400")
        axes[2].plot(cyc, windowed(metrics["prederr_div"]), label="prediction-error divergence", color="#f39c12")
        axes[2].axvline(cutoff, color="black", linestyle="--", linewidth=1)
        axes[2].legend(fontsize=7); axes[2].set_ylabel("level")

        axes[3].plot(cyc, metrics["selfmodel_div"], label="self-model (belief) divergence", color="#27ae60")
        axes[3].axvline(cutoff, color="black", linestyle="--", linewidth=1)
        axes[3].legend(fontsize=7); axes[3].set_ylabel("avg confidence delta")

        axes[4].plot(cyc, windowed([e for e in metrics["entropy_a"]]), label="workspace entropy A", color="#2980b9")
        axes[4].plot(cyc, windowed([e for e in metrics["entropy_b"]]), label="workspace entropy B", color="#e67e22")
        axes[4].plot(cyc, windowed(metrics["flux_contribution"]), label="Flux contribution rate", color="#c0392b", linestyle=":")
        axes[4].axvline(cutoff, color="black", linestyle="--", linewidth=1)
        axes[4].legend(fontsize=7); axes[4].set_ylabel("bits / rate"); axes[4].set_xlabel("cycle")

        fig.suptitle(f"Phase 6.9 — {mode} — seed={args.seed} — Flux OFF after cycle {cutoff}")
        fig.tight_layout()
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(args.out, dpi=120)
        print(f"\nSaved graph to {args.out}")
    except Exception as e:
        print(f"\n(matplotlib graph skipped: {e})")


if __name__ == "__main__":
    main()
